/*
 * Copyright (c) 2014-2015 MongoDB, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the license is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package wrappers

import "syscall"

const (
	FACILITY_WINRM                   = 51
	FACILITY_WINDOWSUPDATE           = 36
	FACILITY_WINDOWS_DEFENDER        = 80
	FACILITY_WINDOWS_CE              = 24
	FACILITY_WINDOWS                 = 8
	FACILITY_USERMODE_VOLMGR         = 56
	FACILITY_USERMODE_VIRTUALIZATION = 55
	FACILITY_USERMODE_VHD            = 58
	FACILITY_URT                     = 19
	FACILITY_UMI                     = 22
	FACILITY_TPM_SOFTWARE            = 41
	FACILITY_TPM_SERVICES            = 40
	FACILITY_SXS                     = 23
	FACILITY_STORAGE                 = 3
	FACILITY_STATE_MANAGEMENT        = 34
	FACILITY_SSPI                    = 9
	FACILITY_SCARD                   = 16
	FACILITY_SHELL                   = 39
	FACILITY_SETUPAPI                = 15
	FACILITY_SECURITY                = 9
	FACILITY_SDIAG                   = 60
	FACILITY_RPC                     = 1
	FACILITY_PLA                     = 48
	FACILITY_OPC                     = 81
	FACILITY_WIN32                   = 7
	FACILITY_CONTROL                 = 10
	FACILITY_WEBSERVICES             = 61
	FACILITY_NULL                    = 0
	FACILITY_NDIS                    = 52
	FACILITY_METADIRECTORY           = 35
	FACILITY_MSMQ                    = 14
	FACILITY_MEDIASERVER             = 13
	FACILITY_INTERNET                = 12
	FACILITY_ITF                     = 4
	FACILITY_USERMODE_HYPERVISOR     = 53
	FACILITY_HTTP                    = 25
	FACILITY_GRAPHICS                = 38
	FACILITY_FWP                     = 50
	FACILITY_FVE                     = 49
	FACILITY_USERMODE_FILTER_MANAGER = 31
	FACILITY_DPLAY                   = 21
	FACILITY_DISPATCH                = 2
	FACILITY_DIRECTORYSERVICE        = 37
	FACILITY_CONFIGURATION           = 33
	FACILITY_COMPLUS                 = 17
	FACILITY_USERMODE_COMMONLOG      = 26
	FACILITY_CMI                     = 54
	FACILITY_CERT                    = 11
	FACILITY_BCD                     = 57
	FACILITY_BACKGROUNDCOPY          = 32
	FACILITY_ACS                     = 20
	FACILITY_AAF                     = 18
)

const (
	ERROR_SUCCESS                                                 syscall.Errno = 0
	ERROR_INVALID_FUNCTION                                        syscall.Errno = 1
	ERROR_FILE_NOT_FOUND                                          syscall.Errno = 2
	ERROR_PATH_NOT_FOUND                                          syscall.Errno = 3
	ERROR_TOO_MANY_OPEN_FILES                                     syscall.Errno = 4
	ERROR_ACCESS_DENIED                                           syscall.Errno = 5
	ERROR_INVALID_HANDLE                                          syscall.Errno = 6
	ERROR_ARENA_TRASHED                                           syscall.Errno = 7
	ERROR_NOT_ENOUGH_MEMORY                                       syscall.Errno = 8
	ERROR_INVALID_BLOCK                                           syscall.Errno = 9
	ERROR_BAD_ENVIRONMENT                                         syscall.Errno = 10
	ERROR_BAD_FORMAT                                              syscall.Errno = 11
	ERROR_INVALID_ACCESS                                          syscall.Errno = 12
	ERROR_INVALID_DATA                                            syscall.Errno = 13
	ERROR_OUTOFMEMORY                                             syscall.Errno = 14
	ERROR_INVALID_DRIVE                                           syscall.Errno = 15
	ERROR_CURRENT_DIRECTORY                                       syscall.Errno = 16
	ERROR_NOT_SAME_DEVICE                                         syscall.Errno = 17
	ERROR_NO_MORE_FILES                                           syscall.Errno = 18
	ERROR_WRITE_PROTECT                                           syscall.Errno = 19
	ERROR_BAD_UNIT                                                syscall.Errno = 20
	ERROR_NOT_READY                                               syscall.Errno = 21
	ERROR_BAD_COMMAND                                             syscall.Errno = 22
	ERROR_CRC                                                     syscall.Errno = 23
	ERROR_BAD_LENGTH                                              syscall.Errno = 24
	ERROR_SEEK                                                    syscall.Errno = 25
	ERROR_NOT_DOS_DISK                                            syscall.Errno = 26
	ERROR_SECTOR_NOT_FOUND                                        syscall.Errno = 27
	ERROR_OUT_OF_PAPER                                            syscall.Errno = 28
	ERROR_WRITE_FAULT                                             syscall.Errno = 29
	ERROR_READ_FAULT                                              syscall.Errno = 30
	ERROR_GEN_FAILURE                                             syscall.Errno = 31
	ERROR_SHARING_VIOLATION                                       syscall.Errno = 32
	ERROR_LOCK_VIOLATION                                          syscall.Errno = 33
	ERROR_WRONG_DISK                                              syscall.Errno = 34
	ERROR_SHARING_BUFFER_EXCEEDED                                 syscall.Errno = 36
	ERROR_HANDLE_EOF                                              syscall.Errno = 38
	ERROR_HANDLE_DISK_FULL                                        syscall.Errno = 39
	ERROR_NOT_SUPPORTED                                           syscall.Errno = 50
	ERROR_REM_NOT_LIST                                            syscall.Errno = 51
	ERROR_DUP_NAME                                                syscall.Errno = 52
	ERROR_BAD_NETPATH                                             syscall.Errno = 53
	ERROR_NETWORK_BUSY                                            syscall.Errno = 54
	ERROR_DEV_NOT_EXIST                                           syscall.Errno = 55
	ERROR_TOO_MANY_CMDS                                           syscall.Errno = 56
	ERROR_ADAP_HDW_ERR                                            syscall.Errno = 57
	ERROR_BAD_NET_RESP                                            syscall.Errno = 58
	ERROR_UNEXP_NET_ERR                                           syscall.Errno = 59
	ERROR_BAD_REM_ADAP                                            syscall.Errno = 60
	ERROR_PRINTQ_FULL                                             syscall.Errno = 61
	ERROR_NO_SPOOL_SPACE                                          syscall.Errno = 62
	ERROR_PRINT_CANCELLED                                         syscall.Errno = 63
	ERROR_NETNAME_DELETED                                         syscall.Errno = 64
	ERROR_NETWORK_ACCESS_DENIED                                   syscall.Errno = 65
	ERROR_BAD_DEV_TYPE                                            syscall.Errno = 66
	ERROR_BAD_NET_NAME                                            syscall.Errno = 67
	ERROR_TOO_MANY_NAMES                                          syscall.Errno = 68
	ERROR_TOO_MANY_SESS                                           syscall.Errno = 69
	ERROR_SHARING_PAUSED                                          syscall.Errno = 70
	ERROR_REQ_NOT_ACCEP                                           syscall.Errno = 71
	ERROR_REDIR_PAUSED                                            syscall.Errno = 72
	ERROR_FILE_EXISTS                                             syscall.Errno = 80
	ERROR_CANNOT_MAKE                                             syscall.Errno = 82
	ERROR_FAIL_I24                                                syscall.Errno = 83
	ERROR_OUT_OF_STRUCTURES                                       syscall.Errno = 84
	ERROR_ALREADY_ASSIGNED                                        syscall.Errno = 85
	ERROR_INVALID_PASSWORD                                        syscall.Errno = 86
	ERROR_INVALID_PARAMETER                                       syscall.Errno = 87
	ERROR_NET_WRITE_FAULT                                         syscall.Errno = 88
	ERROR_NO_PROC_SLOTS                                           syscall.Errno = 89
	ERROR_TOO_MANY_SEMAPHORES                                     syscall.Errno = 100
	ERROR_EXCL_SEM_ALREADY_OWNED                                  syscall.Errno = 101
	ERROR_SEM_IS_SET                                              syscall.Errno = 102
	ERROR_TOO_MANY_SEM_REQUESTS                                   syscall.Errno = 103
	ERROR_INVALID_AT_INTERRUPT_TIME                               syscall.Errno = 104
	ERROR_SEM_OWNER_DIED                                          syscall.Errno = 105
	ERROR_SEM_USER_LIMIT                                          syscall.Errno = 106
	ERROR_DISK_CHANGE                                             syscall.Errno = 107
	ERROR_DRIVE_LOCKED                                            syscall.Errno = 108
	ERROR_BROKEN_PIPE                                             syscall.Errno = 109
	ERROR_OPEN_FAILED                                             syscall.Errno = 110
	ERROR_BUFFER_OVERFLOW                                         syscall.Errno = 111
	ERROR_DISK_FULL                                               syscall.Errno = 112
	ERROR_NO_MORE_SEARCH_HANDLES                                  syscall.Errno = 113
	ERROR_INVALID_TARGET_HANDLE                                   syscall.Errno = 114
	ERROR_INVALID_CATEGORY                                        syscall.Errno = 117
	ERROR_INVALID_VERIFY_SWITCH                                   syscall.Errno = 118
	ERROR_BAD_DRIVER_LEVEL                                        syscall.Errno = 119
	ERROR_CALL_NOT_IMPLEMENTED                                    syscall.Errno = 120
	ERROR_SEM_TIMEOUT                                             syscall.Errno = 121
	ERROR_INSUFFICIENT_BUFFER                                     syscall.Errno = 122
	ERROR_INVALID_NAME                                            syscall.Errno = 123
	ERROR_INVALID_LEVEL                                           syscall.Errno = 124
	ERROR_NO_VOLUME_LABEL                                         syscall.Errno = 125
	ERROR_MOD_NOT_FOUND                                           syscall.Errno = 126
	ERROR_PROC_NOT_FOUND                                          syscall.Errno = 127
	ERROR_WAIT_NO_CHILDREN                                        syscall.Errno = 128
	ERROR_CHILD_NOT_COMPLETE                                      syscall.Errno = 129
	ERROR_DIRECT_ACCESS_HANDLE                                    syscall.Errno = 130
	ERROR_NEGATIVE_SEEK                                           syscall.Errno = 131
	ERROR_SEEK_ON_DEVICE                                          syscall.Errno = 132
	ERROR_IS_JOIN_TARGET                                          syscall.Errno = 133
	ERROR_IS_JOINED                                               syscall.Errno = 134
	ERROR_IS_SUBSTED                                              syscall.Errno = 135
	ERROR_NOT_JOINED                                              syscall.Errno = 136
	ERROR_NOT_SUBSTED                                             syscall.Errno = 137
	ERROR_JOIN_TO_JOIN                                            syscall.Errno = 138
	ERROR_SUBST_TO_SUBST                                          syscall.Errno = 139
	ERROR_JOIN_TO_SUBST                                           syscall.Errno = 140
	ERROR_SUBST_TO_JOIN                                           syscall.Errno = 141
	ERROR_BUSY_DRIVE                                              syscall.Errno = 142
	ERROR_SAME_DRIVE                                              syscall.Errno = 143
	ERROR_DIR_NOT_ROOT                                            syscall.Errno = 144
	ERROR_DIR_NOT_EMPTY                                           syscall.Errno = 145
	ERROR_IS_SUBST_PATH                                           syscall.Errno = 146
	ERROR_IS_JOIN_PATH                                            syscall.Errno = 147
	ERROR_PATH_BUSY                                               syscall.Errno = 148
	ERROR_IS_SUBST_TARGET                                         syscall.Errno = 149
	ERROR_SYSTEM_TRACE                                            syscall.Errno = 150
	ERROR_INVALID_EVENT_COUNT                                     syscall.Errno = 151
	ERROR_TOO_MANY_MUXWAITERS                                     syscall.Errno = 152
	ERROR_INVALID_LIST_FORMAT                                     syscall.Errno = 153
	ERROR_LABEL_TOO_LONG                                          syscall.Errno = 154
	ERROR_TOO_MANY_TCBS                                           syscall.Errno = 155
	ERROR_SIGNAL_REFUSED                                          syscall.Errno = 156
	ERROR_DISCARDED                                               syscall.Errno = 157
	ERROR_NOT_LOCKED                                              syscall.Errno = 158
	ERROR_BAD_THREADID_ADDR                                       syscall.Errno = 159
	ERROR_BAD_ARGUMENTS                                           syscall.Errno = 160
	ERROR_BAD_PATHNAME                                            syscall.Errno = 161
	ERROR_SIGNAL_PENDING                                          syscall.Errno = 162
	ERROR_MAX_THRDS_REACHED                                       syscall.Errno = 164
	ERROR_LOCK_FAILED                                             syscall.Errno = 167
	ERROR_BUSY                                                    syscall.Errno = 170
	ERROR_CANCEL_VIOLATION                                        syscall.Errno = 173
	ERROR_ATOMIC_LOCKS_NOT_SUPPORTED                              syscall.Errno = 174
	ERROR_INVALID_SEGMENT_NUMBER                                  syscall.Errno = 180
	ERROR_INVALID_ORDINAL                                         syscall.Errno = 182
	ERROR_ALREADY_EXISTS                                          syscall.Errno = 183
	ERROR_INVALID_FLAG_NUMBER                                     syscall.Errno = 186
	ERROR_SEM_NOT_FOUND                                           syscall.Errno = 187
	ERROR_INVALID_STARTING_CODESEG                                syscall.Errno = 188
	ERROR_INVALID_STACKSEG                                        syscall.Errno = 189
	ERROR_INVALID_MODULETYPE                                      syscall.Errno = 190
	ERROR_INVALID_EXE_SIGNATURE                                   syscall.Errno = 191
	ERROR_EXE_MARKED_INVALID                                      syscall.Errno = 192
	ERROR_BAD_EXE_FORMAT                                          syscall.Errno = 193
	ERROR_ITERATED_DATA_EXCEEDS_64k                               syscall.Errno = 194
	ERROR_INVALID_MINALLOCSIZE                                    syscall.Errno = 195
	ERROR_DYNLINK_FROM_INVALID_RING                               syscall.Errno = 196
	ERROR_IOPL_NOT_ENABLED                                        syscall.Errno = 197
	ERROR_INVALID_SEGDPL                                          syscall.Errno = 198
	ERROR_AUTODATASEG_EXCEEDS_64k                                 syscall.Errno = 199
	ERROR_RING2SEG_MUST_BE_MOVABLE                                syscall.Errno = 200
	ERROR_RELOC_CHAIN_XEEDS_SEGLIM                                syscall.Errno = 201
	ERROR_INFLOOP_IN_RELOC_CHAIN                                  syscall.Errno = 202
	ERROR_ENVVAR_NOT_FOUND                                        syscall.Errno = 203
	ERROR_NO_SIGNAL_SENT                                          syscall.Errno = 205
	ERROR_FILENAME_EXCED_RANGE                                    syscall.Errno = 206
	ERROR_RING2_STACK_IN_USE                                      syscall.Errno = 207
	ERROR_META_EXPANSION_TOO_LONG                                 syscall.Errno = 208
	ERROR_INVALID_SIGNAL_NUMBER                                   syscall.Errno = 209
	ERROR_THREAD_1_INACTIVE                                       syscall.Errno = 210
	ERROR_LOCKED                                                  syscall.Errno = 212
	ERROR_TOO_MANY_MODULES                                        syscall.Errno = 214
	ERROR_NESTING_NOT_ALLOWED                                     syscall.Errno = 215
	ERROR_EXE_MACHINE_TYPE_MISMATCH                               syscall.Errno = 216
	ERROR_EXE_CANNOT_MODIFY_SIGNED_BINARY                         syscall.Errno = 217
	ERROR_EXE_CANNOT_MODIFY_STRONG_SIGNED_BINARY                  syscall.Errno = 218
	ERROR_FILE_CHECKED_OUT                                        syscall.Errno = 220
	ERROR_CHECKOUT_REQUIRED                                       syscall.Errno = 221
	ERROR_BAD_FILE_TYPE                                           syscall.Errno = 222
	ERROR_FILE_TOO_LARGE                                          syscall.Errno = 223
	ERROR_FORMS_AUTH_REQUIRED                                     syscall.Errno = 224
	ERROR_VIRUS_INFECTED                                          syscall.Errno = 225
	ERROR_VIRUS_DELETED                                           syscall.Errno = 226
	ERROR_PIPE_LOCAL                                              syscall.Errno = 229
	ERROR_BAD_PIPE                                                syscall.Errno = 230
	ERROR_PIPE_BUSY                                               syscall.Errno = 231
	ERROR_NO_DATA                                                 syscall.Errno = 232
	ERROR_PIPE_NOT_CONNECTED                                      syscall.Errno = 233
	ERROR_MORE_DATA                                               syscall.Errno = 234
	ERROR_VC_DISCONNECTED                                         syscall.Errno = 240
	ERROR_INVALID_EA_NAME                                         syscall.Errno = 254
	ERROR_EA_LIST_INCONSISTENT                                    syscall.Errno = 255
	WAIT_TIMEOUT                                                  syscall.Errno = 258
	ERROR_NO_MORE_ITEMS                                           syscall.Errno = 259
	ERROR_CANNOT_COPY                                             syscall.Errno = 266
	ERROR_DIRECTORY                                               syscall.Errno = 267
	ERROR_EAS_DIDNT_FIT                                           syscall.Errno = 275
	ERROR_EA_FILE_CORRUPT                                         syscall.Errno = 276
	ERROR_EA_TABLE_FULL                                           syscall.Errno = 277
	ERROR_INVALID_EA_HANDLE                                       syscall.Errno = 278
	ERROR_EAS_NOT_SUPPORTED                                       syscall.Errno = 282
	ERROR_NOT_OWNER                                               syscall.Errno = 288
	ERROR_TOO_MANY_POSTS                                          syscall.Errno = 298
	ERROR_PARTIAL_COPY                                            syscall.Errno = 299
	ERROR_OPLOCK_NOT_GRANTED                                      syscall.Errno = 300
	ERROR_INVALID_OPLOCK_PROTOCOL                                 syscall.Errno = 301
	ERROR_DISK_TOO_FRAGMENTED                                     syscall.Errno = 302
	ERROR_DELETE_PENDING                                          syscall.Errno = 303
	ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING    syscall.Errno = 304
	ERROR_SHORT_NAMES_NOT_ENABLED_ON_VOLUME                       syscall.Errno = 305
	ERROR_SECURITY_STREAM_IS_INCONSISTENT                         syscall.Errno = 306
	ERROR_INVALID_LOCK_RANGE                                      syscall.Errno = 307
	ERROR_IMAGE_SUBSYSTEM_NOT_PRESENT                             syscall.Errno = 308
	ERROR_NOTIFICATION_GUID_ALREADY_DEFINED                       syscall.Errno = 309
	ERROR_MR_MID_NOT_FOUND                                        syscall.Errno = 317
	ERROR_SCOPE_NOT_FOUND                                         syscall.Errno = 318
	ERROR_FAIL_NOACTION_REBOOT                                    syscall.Errno = 350
	ERROR_FAIL_SHUTDOWN                                           syscall.Errno = 351
	ERROR_FAIL_RESTART                                            syscall.Errno = 352
	ERROR_MAX_SESSIONS_REACHED                                    syscall.Errno = 353
	ERROR_THREAD_MODE_ALREADY_BACKGROUND                          syscall.Errno = 400
	ERROR_THREAD_MODE_NOT_BACKGROUND                              syscall.Errno = 401
	ERROR_PROCESS_MODE_ALREADY_BACKGROUND                         syscall.Errno = 402
	ERROR_PROCESS_MODE_NOT_BACKGROUND                             syscall.Errno = 403
	ERROR_INVALID_ADDRESS                                         syscall.Errno = 487
	ERROR_USER_PROFILE_LOAD                                       syscall.Errno = 500
	ERROR_ARITHMETIC_OVERFLOW                                     syscall.Errno = 534
	ERROR_PIPE_CONNECTED                                          syscall.Errno = 535
	ERROR_PIPE_LISTENING                                          syscall.Errno = 536
	ERROR_VERIFIER_STOP                                           syscall.Errno = 537
	ERROR_ABIOS_ERROR                                             syscall.Errno = 538
	ERROR_WX86_WARNING                                            syscall.Errno = 539
	ERROR_WX86_ERROR                                              syscall.Errno = 540
	ERROR_TIMER_NOT_CANCELED                                      syscall.Errno = 541
	ERROR_UNWIND                                                  syscall.Errno = 542
	ERROR_BAD_STACK                                               syscall.Errno = 543
	ERROR_INVALID_UNWIND_TARGET                                   syscall.Errno = 544
	ERROR_INVALID_PORT_ATTRIBUTES                                 syscall.Errno = 545
	ERROR_PORT_MESSAGE_TOO_LONG                                   syscall.Errno = 546
	ERROR_INVALID_QUOTA_LOWER                                     syscall.Errno = 547
	ERROR_DEVICE_ALREADY_ATTACHED                                 syscall.Errno = 548
	ERROR_INSTRUCTION_MISALIGNMENT                                syscall.Errno = 549
	ERROR_PROFILING_NOT_STARTED                                   syscall.Errno = 550
	ERROR_PROFILING_NOT_STOPPED                                   syscall.Errno = 551
	ERROR_COULD_NOT_INTERPRET                                     syscall.Errno = 552
	ERROR_PROFILING_AT_LIMIT                                      syscall.Errno = 553
	ERROR_CANT_WAIT                                               syscall.Errno = 554
	ERROR_CANT_TERMINATE_SELF                                     syscall.Errno = 555
	ERROR_UNEXPECTED_MM_CREATE_ERR                                syscall.Errno = 556
	ERROR_UNEXPECTED_MM_MAP_ERR                                   syscall.Errno = 557
	ERROR_UNEXPECTED_MM_EXTEND_ERR                                syscall.Errno = 558
	ERROR_BAD_FUNCTION_TABLE                                      syscall.Errno = 559
	ERROR_NO_GUID_TRANSLATION                                     syscall.Errno = 560
	ERROR_INVALID_LDT_SIZE                                        syscall.Errno = 561
	ERROR_INVALID_LDT_OFFSET                                      syscall.Errno = 563
	ERROR_INVALID_LDT_DESCRIPTOR                                  syscall.Errno = 564
	ERROR_TOO_MANY_THREADS                                        syscall.Errno = 565
	ERROR_THREAD_NOT_IN_PROCESS                                   syscall.Errno = 566
	ERROR_PAGEFILE_QUOTA_EXCEEDED                                 syscall.Errno = 567
	ERROR_LOGON_SERVER_CONFLICT                                   syscall.Errno = 568
	ERROR_SYNCHRONIZATION_REQUIRED                                syscall.Errno = 569
	ERROR_NET_OPEN_FAILED                                         syscall.Errno = 570
	ERROR_IO_PRIVILEGE_FAILED                                     syscall.Errno = 571
	ERROR_CONTROL_C_EXIT                                          syscall.Errno = 572
	ERROR_MISSING_SYSTEMFILE                                      syscall.Errno = 573
	ERROR_UNHANDLED_EXCEPTION                                     syscall.Errno = 574
	ERROR_APP_INIT_FAILURE                                        syscall.Errno = 575
	ERROR_PAGEFILE_CREATE_FAILED                                  syscall.Errno = 576
	ERROR_INVALID_IMAGE_HASH                                      syscall.Errno = 577
	ERROR_NO_PAGEFILE                                             syscall.Errno = 578
	ERROR_ILLEGAL_FLOAT_CONTEXT                                   syscall.Errno = 579
	ERROR_NO_EVENT_PAIR                                           syscall.Errno = 580
	ERROR_DOMAIN_CTRLR_CONFIG_ERROR                               syscall.Errno = 581
	ERROR_ILLEGAL_CHARACTER                                       syscall.Errno = 582
	ERROR_UNDEFINED_CHARACTER                                     syscall.Errno = 583
	ERROR_FLOPPY_VOLUME                                           syscall.Errno = 584
	ERROR_BIOS_FAILED_TO_CONNECT_INTERRUPT                        syscall.Errno = 585
	ERROR_BACKUP_CONTROLLER                                       syscall.Errno = 586
	ERROR_MUTANT_LIMIT_EXCEEDED                                   syscall.Errno = 587
	ERROR_FS_DRIVER_REQUIRED                                      syscall.Errno = 588
	ERROR_CANNOT_LOAD_REGISTRY_FILE                               syscall.Errno = 589
	ERROR_DEBUG_ATTACH_FAILED                                     syscall.Errno = 590
	ERROR_SYSTEM_PROCESS_TERMINATED                               syscall.Errno = 591
	ERROR_DATA_NOT_ACCEPTED                                       syscall.Errno = 592
	ERROR_VDM_HARD_ERROR                                          syscall.Errno = 593
	ERROR_DRIVER_CANCEL_TIMEOUT                                   syscall.Errno = 594
	ERROR_REPLY_MESSAGE_MISMATCH                                  syscall.Errno = 595
	ERROR_LOST_WRITEBEHIND_DATA                                   syscall.Errno = 596
	ERROR_CLIENT_SERVER_PARAMETERS_INVALID                        syscall.Errno = 597
	ERROR_NOT_TINY_STREAM                                         syscall.Errno = 598
	ERROR_STACK_OVERFLOW_READ                                     syscall.Errno = 599
	ERROR_CONVERT_TO_LARGE                                        syscall.Errno = 600
	ERROR_FOUND_OUT_OF_SCOPE                                      syscall.Errno = 601
	ERROR_ALLOCATE_BUCKET                                         syscall.Errno = 602
	ERROR_MARSHALL_OVERFLOW                                       syscall.Errno = 603
	ERROR_INVALID_VARIANT                                         syscall.Errno = 604
	ERROR_BAD_COMPRESSION_BUFFER                                  syscall.Errno = 605
	ERROR_AUDIT_FAILED                                            syscall.Errno = 606
	ERROR_TIMER_RESOLUTION_NOT_SET                                syscall.Errno = 607
	ERROR_INSUFFICIENT_LOGON_INFO                                 syscall.Errno = 608
	ERROR_BAD_DLL_ENTRYPOINT                                      syscall.Errno = 609
	ERROR_BAD_SERVICE_ENTRYPOINT                                  syscall.Errno = 610
	ERROR_IP_ADDRESS_CONFLICT1                                    syscall.Errno = 611
	ERROR_IP_ADDRESS_CONFLICT2                                    syscall.Errno = 612
	ERROR_REGISTRY_QUOTA_LIMIT                                    syscall.Errno = 613
	ERROR_NO_CALLBACK_ACTIVE                                      syscall.Errno = 614
	ERROR_PWD_TOO_SHORT                                           syscall.Errno = 615
	ERROR_PWD_TOO_RECENT                                          syscall.Errno = 616
	ERROR_PWD_HISTORY_CONFLICT                                    syscall.Errno = 617
	ERROR_UNSUPPORTED_COMPRESSION                                 syscall.Errno = 618
	ERROR_INVALID_HW_PROFILE                                      syscall.Errno = 619
	ERROR_INVALID_PLUGPLAY_DEVICE_PATH                            syscall.Errno = 620
	ERROR_QUOTA_LIST_INCONSISTENT                                 syscall.Errno = 621
	ERROR_EVALUATION_EXPIRATION                                   syscall.Errno = 622
	ERROR_ILLEGAL_DLL_RELOCATION                                  syscall.Errno = 623
	ERROR_DLL_INIT_FAILED_LOGOFF                                  syscall.Errno = 624
	ERROR_VALIDATE_CONTINUE                                       syscall.Errno = 625
	ERROR_NO_MORE_MATCHES                                         syscall.Errno = 626
	ERROR_RANGE_LIST_CONFLICT                                     syscall.Errno = 627
	ERROR_SERVER_SID_MISMATCH                                     syscall.Errno = 628
	ERROR_CANT_ENABLE_DENY_ONLY                                   syscall.Errno = 629
	ERROR_FLOAT_MULTIPLE_FAULTS                                   syscall.Errno = 630
	ERROR_FLOAT_MULTIPLE_TRAPS                                    syscall.Errno = 631
	ERROR_NOINTERFACE                                             syscall.Errno = 632
	ERROR_DRIVER_FAILED_SLEEP                                     syscall.Errno = 633
	ERROR_CORRUPT_SYSTEM_FILE                                     syscall.Errno = 634
	ERROR_COMMITMENT_MINIMUM                                      syscall.Errno = 635
	ERROR_PNP_RESTART_ENUMERATION                                 syscall.Errno = 636
	ERROR_SYSTEM_IMAGE_BAD_SIGNATURE                              syscall.Errno = 637
	ERROR_PNP_REBOOT_REQUIRED                                     syscall.Errno = 638
	ERROR_INSUFFICIENT_POWER                                      syscall.Errno = 639
	ERROR_MULTIPLE_FAULT_VIOLATION                                syscall.Errno = 640
	ERROR_SYSTEM_SHUTDOWN                                         syscall.Errno = 641
	ERROR_PORT_NOT_SET                                            syscall.Errno = 642
	ERROR_DS_VERSION_CHECK_FAILURE                                syscall.Errno = 643
	ERROR_RANGE_NOT_FOUND                                         syscall.Errno = 644
	ERROR_NOT_SAFE_MODE_DRIVER                                    syscall.Errno = 646
	ERROR_FAILED_DRIVER_ENTRY                                     syscall.Errno = 647
	ERROR_DEVICE_ENUMERATION_ERROR                                syscall.Errno = 648
	ERROR_MOUNT_POINT_NOT_RESOLVED                                syscall.Errno = 649
	ERROR_INVALID_DEVICE_OBJECT_PARAMETER                         syscall.Errno = 650
	ERROR_MCA_OCCURED                                             syscall.Errno = 651
	ERROR_DRIVER_DATABASE_ERROR                                   syscall.Errno = 652
	ERROR_SYSTEM_HIVE_TOO_LARGE                                   syscall.Errno = 653
	ERROR_DRIVER_FAILED_PRIOR_UNLOAD                              syscall.Errno = 654
	ERROR_VOLSNAP_PREPARE_HIBERNATE                               syscall.Errno = 655
	ERROR_HIBERNATION_FAILURE                                     syscall.Errno = 656
	ERROR_FILE_SYSTEM_LIMITATION                                  syscall.Errno = 665
	ERROR_ASSERTION_FAILURE                                       syscall.Errno = 668
	ERROR_ACPI_ERROR                                              syscall.Errno = 669
	ERROR_WOW_ASSERTION                                           syscall.Errno = 670
	ERROR_PNP_BAD_MPS_TABLE                                       syscall.Errno = 671
	ERROR_PNP_TRANSLATION_FAILED                                  syscall.Errno = 672
	ERROR_PNP_IRQ_TRANSLATION_FAILED                              syscall.Errno = 673
	ERROR_PNP_INVALID_ID                                          syscall.Errno = 674
	ERROR_WAKE_SYSTEM_DEBUGGER                                    syscall.Errno = 675
	ERROR_HANDLES_CLOSED                                          syscall.Errno = 676
	ERROR_EXTRANEOUS_INFORMATION                                  syscall.Errno = 677
	ERROR_RXACT_COMMIT_NECESSARY                                  syscall.Errno = 678
	ERROR_MEDIA_CHECK                                             syscall.Errno = 679
	ERROR_GUID_SUBSTITUTION_MADE                                  syscall.Errno = 680
	ERROR_STOPPED_ON_SYMLINK                                      syscall.Errno = 681
	ERROR_LONGJUMP                                                syscall.Errno = 682
	ERROR_PLUGPLAY_QUERY_VETOED                                   syscall.Errno = 683
	ERROR_UNWIND_CONSOLIDATE                                      syscall.Errno = 684
	ERROR_REGISTRY_HIVE_RECOVERED                                 syscall.Errno = 685
	ERROR_DLL_MIGHT_BE_INSECURE                                   syscall.Errno = 686
	ERROR_DLL_MIGHT_BE_INCOMPATIBLE                               syscall.Errno = 687
	ERROR_DBG_EXCEPTION_NOT_HANDLED                               syscall.Errno = 688
	ERROR_DBG_REPLY_LATER                                         syscall.Errno = 689
	ERROR_DBG_UNABLE_TO_PROVIDE_HANDLE                            syscall.Errno = 690
	ERROR_DBG_TERMINATE_THREAD                                    syscall.Errno = 691
	ERROR_DBG_TERMINATE_PROCESS                                   syscall.Errno = 692
	ERROR_DBG_CONTROL_C                                           syscall.Errno = 693
	ERROR_DBG_PRINTEXCEPTION_C                                    syscall.Errno = 694
	ERROR_DBG_RIPEXCEPTION                                        syscall.Errno = 695
	ERROR_DBG_CONTROL_BREAK                                       syscall.Errno = 696
	ERROR_DBG_COMMAND_EXCEPTION                                   syscall.Errno = 697
	ERROR_OBJECT_NAME_EXISTS                                      syscall.Errno = 698
	ERROR_THREAD_WAS_SUSPENDED                                    syscall.Errno = 699
	ERROR_IMAGE_NOT_AT_BASE                                       syscall.Errno = 700
	ERROR_RXACT_STATE_CREATED                                     syscall.Errno = 701
	ERROR_SEGMENT_NOTIFICATION                                    syscall.Errno = 702
	ERROR_BAD_CURRENT_DIRECTORY                                   syscall.Errno = 703
	ERROR_FT_READ_RECOVERY_FROM_BACKUP                            syscall.Errno = 704
	ERROR_FT_WRITE_RECOVERY                                       syscall.Errno = 705
	ERROR_IMAGE_MACHINE_TYPE_MISMATCH                             syscall.Errno = 706
	ERROR_RECEIVE_PARTIAL                                         syscall.Errno = 707
	ERROR_RECEIVE_EXPEDITED                                       syscall.Errno = 708
	ERROR_RECEIVE_PARTIAL_EXPEDITED                               syscall.Errno = 709
	ERROR_EVENT_DONE                                              syscall.Errno = 710
	ERROR_EVENT_PENDING                                           syscall.Errno = 711
	ERROR_CHECKING_FILE_SYSTEM                                    syscall.Errno = 712
	ERROR_FATAL_APP_EXIT                                          syscall.Errno = 713
	ERROR_PREDEFINED_HANDLE                                       syscall.Errno = 714
	ERROR_WAS_UNLOCKED                                            syscall.Errno = 715
	ERROR_SERVICE_NOTIFICATION                                    syscall.Errno = 716
	ERROR_WAS_LOCKED                                              syscall.Errno = 717
	ERROR_LOG_HARD_ERROR                                          syscall.Errno = 718
	ERROR_ALREADY_WIN32                                           syscall.Errno = 719
	ERROR_IMAGE_MACHINE_TYPE_MISMATCH_EXE                         syscall.Errno = 720
	ERROR_NO_YIELD_PERFORMED                                      syscall.Errno = 721
	ERROR_TIMER_RESUME_IGNORED                                    syscall.Errno = 722
	ERROR_ARBITRATION_UNHANDLED                                   syscall.Errno = 723
	ERROR_CARDBUS_NOT_SUPPORTED                                   syscall.Errno = 724
	ERROR_MP_PROCESSOR_MISMATCH                                   syscall.Errno = 725
	ERROR_HIBERNATED                                              syscall.Errno = 726
	ERROR_RESUME_HIBERNATION                                      syscall.Errno = 727
	ERROR_FIRMWARE_UPDATED                                        syscall.Errno = 728
	ERROR_DRIVERS_LEAKING_LOCKED_PAGES                            syscall.Errno = 729
	ERROR_WAKE_SYSTEM                                             syscall.Errno = 730
	ERROR_WAIT_1                                                  syscall.Errno = 731
	ERROR_WAIT_2                                                  syscall.Errno = 732
	ERROR_WAIT_3                                                  syscall.Errno = 733
	ERROR_WAIT_63                                                 syscall.Errno = 734
	ERROR_ABANDONED_WAIT_0                                        syscall.Errno = 735
	ERROR_ABANDONED_WAIT_63                                       syscall.Errno = 736
	ERROR_USER_APC                                                syscall.Errno = 737
	ERROR_KERNEL_APC                                              syscall.Errno = 738
	ERROR_ALERTED                                                 syscall.Errno = 739
	ERROR_ELEVATION_REQUIRED                                      syscall.Errno = 740
	ERROR_REPARSE                                                 syscall.Errno = 741
	ERROR_OPLOCK_BREAK_IN_PROGRESS                                syscall.Errno = 742
	ERROR_VOLUME_MOUNTED                                          syscall.Errno = 743
	ERROR_RXACT_COMMITTED                                         syscall.Errno = 744
	ERROR_NOTIFY_CLEANUP                                          syscall.Errno = 745
	ERROR_PRIMARY_TRANSPORT_CONNECT_FAILED                        syscall.Errno = 746
	ERROR_PAGE_FAULT_TRANSITION                                   syscall.Errno = 747
	ERROR_PAGE_FAULT_DEMAND_ZERO                                  syscall.Errno = 748
	ERROR_PAGE_FAULT_COPY_ON_WRITE                                syscall.Errno = 749
	ERROR_PAGE_FAULT_GUARD_PAGE                                   syscall.Errno = 750
	ERROR_PAGE_FAULT_PAGING_FILE                                  syscall.Errno = 751
	ERROR_CACHE_PAGE_LOCKED                                       syscall.Errno = 752
	ERROR_CRASH_DUMP                                              syscall.Errno = 753
	ERROR_BUFFER_ALL_ZEROS                                        syscall.Errno = 754
	ERROR_REPARSE_OBJECT                                          syscall.Errno = 755
	ERROR_RESOURCE_REQUIREMENTS_CHANGED                           syscall.Errno = 756
	ERROR_TRANSLATION_COMPLETE                                    syscall.Errno = 757
	ERROR_NOTHING_TO_TERMINATE                                    syscall.Errno = 758
	ERROR_PROCESS_NOT_IN_JOB                                      syscall.Errno = 759
	ERROR_PROCESS_IN_JOB                                          syscall.Errno = 760
	ERROR_VOLSNAP_HIBERNATE_READY                                 syscall.Errno = 761
	ERROR_FSFILTER_OP_COMPLETED_SUCCESSFULLY                      syscall.Errno = 762
	ERROR_INTERRUPT_VECTOR_ALREADY_CONNECTED                      syscall.Errno = 763
	ERROR_INTERRUPT_STILL_CONNECTED                               syscall.Errno = 764
	ERROR_WAIT_FOR_OPLOCK                                         syscall.Errno = 765
	ERROR_DBG_EXCEPTION_HANDLED                                   syscall.Errno = 766
	ERROR_DBG_CONTINUE                                            syscall.Errno = 767
	ERROR_CALLBACK_POP_STACK                                      syscall.Errno = 768
	ERROR_COMPRESSION_DISABLED                                    syscall.Errno = 769
	ERROR_CANTFETCHBACKWARDS                                      syscall.Errno = 770
	ERROR_CANTSCROLLBACKWARDS                                     syscall.Errno = 771
	ERROR_ROWSNOTRELEASED                                         syscall.Errno = 772
	ERROR_BAD_ACCESSOR_FLAGS                                      syscall.Errno = 773
	ERROR_ERRORS_ENCOUNTERED                                      syscall.Errno = 774
	ERROR_NOT_CAPABLE                                             syscall.Errno = 775
	ERROR_REQUEST_OUT_OF_SEQUENCE                                 syscall.Errno = 776
	ERROR_VERSION_PARSE_ERROR                                     syscall.Errno = 777
	ERROR_BADSTARTPOSITION                                        syscall.Errno = 778
	ERROR_MEMORY_HARDWARE                                         syscall.Errno = 779
	ERROR_DISK_REPAIR_DISABLED                                    syscall.Errno = 780
	ERROR_INSUFFICIENT_RESOURCE_FOR_SPECIFIED_SHARED_SECTION_SIZE syscall.Errno = 781
	ERROR_SYSTEM_POWERSTATE_TRANSITION                            syscall.Errno = 782
	ERROR_SYSTEM_POWERSTATE_COMPLEX_TRANSITION                    syscall.Errno = 783
	ERROR_MCA_EXCEPTION                                           syscall.Errno = 784
	ERROR_ACCESS_AUDIT_BY_POLICY                                  syscall.Errno = 785
	ERROR_ACCESS_DISABLED_NO_SAFER_UI_BY_POLICY                   syscall.Errno = 786
	ERROR_ABANDON_HIBERFILE                                       syscall.Errno = 787
	ERROR_LOST_WRITEBEHIND_DATA_NETWORK_DISCONNECTED              syscall.Errno = 788
	ERROR_LOST_WRITEBEHIND_DATA_NETWORK_SERVER_ERROR              syscall.Errno = 789
	ERROR_LOST_WRITEBEHIND_DATA_LOCAL_DISK_ERROR                  syscall.Errno = 790
	ERROR_BAD_MCFG_TABLE                                          syscall.Errno = 791
	ERROR_OPLOCK_SWITCHED_TO_NEW_HANDLE                           syscall.Errno = 800
	ERROR_CANNOT_GRANT_REQUESTED_OPLOCK                           syscall.Errno = 801
	ERROR_CANNOT_BREAK_OPLOCK                                     syscall.Errno = 802
	ERROR_OPLOCK_HANDLE_CLOSED                                    syscall.Errno = 803
	ERROR_NO_ACE_CONDITION                                        syscall.Errno = 804
	ERROR_INVALID_ACE_CONDITION                                   syscall.Errno = 805
	ERROR_EA_ACCESS_DENIED                                        syscall.Errno = 994
	ERROR_OPERATION_ABORTED                                       syscall.Errno = 995
	ERROR_IO_INCOMPLETE                                           syscall.Errno = 996
	ERROR_IO_PENDING                                              syscall.Errno = 997
	ERROR_NOACCESS                                                syscall.Errno = 998
	ERROR_SWAPERROR                                               syscall.Errno = 999
	ERROR_STACK_OVERFLOW                                          syscall.Errno = 1001
	ERROR_INVALID_MESSAGE                                         syscall.Errno = 1002
	ERROR_CAN_NOT_COMPLETE                                        syscall.Errno = 1003
	ERROR_INVALID_FLAGS                                           syscall.Errno = 1004
	ERROR_UNRECOGNIZED_VOLUME                                     syscall.Errno = 1005
	ERROR_FILE_INVALID                                            syscall.Errno = 1006
	ERROR_FULLSCREEN_MODE                                         syscall.Errno = 1007
	ERROR_NO_TOKEN                                                syscall.Errno = 1008
	ERROR_BADDB                                                   syscall.Errno = 1009
	ERROR_BADKEY                                                  syscall.Errno = 1010
	ERROR_CANTOPEN                                                syscall.Errno = 1011
	ERROR_CANTREAD                                                syscall.Errno = 1012
	ERROR_CANTWRITE                                               syscall.Errno = 1013
	ERROR_REGISTRY_RECOVERED                                      syscall.Errno = 1014
	ERROR_REGISTRY_CORRUPT                                        syscall.Errno = 1015
	ERROR_REGISTRY_IO_FAILED                                      syscall.Errno = 1016
	ERROR_NOT_REGISTRY_FILE                                       syscall.Errno = 1017
	ERROR_KEY_DELETED                                             syscall.Errno = 1018
	ERROR_NO_LOG_SPACE                                            syscall.Errno = 1019
	ERROR_KEY_HAS_CHILDREN                                        syscall.Errno = 1020
	ERROR_CHILD_MUST_BE_VOLATILE                                  syscall.Errno = 1021
	ERROR_NOTIFY_ENUM_DIR                                         syscall.Errno = 1022
	ERROR_DEPENDENT_SERVICES_RUNNING                              syscall.Errno = 1051
	ERROR_INVALID_SERVICE_CONTROL                                 syscall.Errno = 1052
	ERROR_SERVICE_REQUEST_TIMEOUT                                 syscall.Errno = 1053
	ERROR_SERVICE_NO_THREAD                                       syscall.Errno = 1054
	ERROR_SERVICE_DATABASE_LOCKED                                 syscall.Errno = 1055
	ERROR_SERVICE_ALREADY_RUNNING                                 syscall.Errno = 1056
	ERROR_INVALID_SERVICE_ACCOUNT                                 syscall.Errno = 1057
	ERROR_SERVICE_DISABLED                                        syscall.Errno = 1058
	ERROR_CIRCULAR_DEPENDENCY                                     syscall.Errno = 1059
	ERROR_SERVICE_DOES_NOT_EXIST                                  syscall.Errno = 1060
	ERROR_SERVICE_CANNOT_ACCEPT_CTRL                              syscall.Errno = 1061
	ERROR_SERVICE_NOT_ACTIVE                                      syscall.Errno = 1062
	ERROR_FAILED_SERVICE_CONTROLLER_CONNECT                       syscall.Errno = 1063
	ERROR_EXCEPTION_IN_SERVICE                                    syscall.Errno = 1064
	ERROR_DATABASE_DOES_NOT_EXIST                                 syscall.Errno = 1065
	ERROR_SERVICE_SPECIFIC_ERROR                                  syscall.Errno = 1066
	ERROR_PROCESS_ABORTED                                         syscall.Errno = 1067
	ERROR_SERVICE_DEPENDENCY_FAIL                                 syscall.Errno = 1068
	ERROR_SERVICE_LOGON_FAILED                                    syscall.Errno = 1069
	ERROR_SERVICE_START_HANG                                      syscall.Errno = 1070
	ERROR_INVALID_SERVICE_LOCK                                    syscall.Errno = 1071
	ERROR_SERVICE_MARKED_FOR_DELETE                               syscall.Errno = 1072
	ERROR_SERVICE_EXISTS                                          syscall.Errno = 1073
	ERROR_ALREADY_RUNNING_LKG                                     syscall.Errno = 1074
	ERROR_SERVICE_DEPENDENCY_DELETED                              syscall.Errno = 1075
	ERROR_BOOT_ALREADY_ACCEPTED                                   syscall.Errno = 1076
	ERROR_SERVICE_NEVER_STARTED                                   syscall.Errno = 1077
	ERROR_DUPLICATE_SERVICE_NAME                                  syscall.Errno = 1078
	ERROR_DIFFERENT_SERVICE_ACCOUNT                               syscall.Errno = 1079
	ERROR_CANNOT_DETECT_DRIVER_FAILURE                            syscall.Errno = 1080
	ERROR_CANNOT_DETECH_PROCESS_ABORT                             syscall.Errno = 1081
	ERROR_NO_RECOVERY_PROGRAM                                     syscall.Errno = 1082
	ERROR_SERVICE_NOT_IN_EXE                                      syscall.Errno = 1083
	ERROR_NOT_SAFEBOOT_SERVICE                                    syscall.Errno = 1084
	ERROR_END_OF_MEDIA                                            syscall.Errno = 1100
	ERROR_FILEMARK_DETECTED                                       syscall.Errno = 1101
	ERROR_BEGINNING_OF_MEDIA                                      syscall.Errno = 1102
	ERROR_SETMARK_DETECTED                                        syscall.Errno = 1103
	ERROR_NO_DATA_DETECTED                                        syscall.Errno = 1104
	ERROR_PARTITION_FAILURE                                       syscall.Errno = 1105
	ERROR_INVALID_BLOCK_LENGTH                                    syscall.Errno = 1106
	ERROR_DEVICE_NOT_PARTITIONED                                  syscall.Errno = 1107
	ERROR_UNABLE_TO_LOCK_MEDIA                                    syscall.Errno = 1108
	ERROR_UNABLE_TO_UNLOAD_MEDIA                                  syscall.Errno = 1109
	ERROR_MEDIA_CHANGED                                           syscall.Errno = 1110
	ERROR_BUS_RESET                                               syscall.Errno = 1111
	ERROR_NO_MEDIA_IN_DRIVE                                       syscall.Errno = 1112
	ERROR_NO_UNICODE_TRANSLATION                                  syscall.Errno = 1113
	ERROR_DLL_INIT_FAILED                                         syscall.Errno = 1114
	ERROR_SHUTDOWN_IN_PROGRESS                                    syscall.Errno = 1115
	ERROR_NO_SHUTDOWN_IN_PROGRESS                                 syscall.Errno = 1116
	ERROR_IO_DEVICE                                               syscall.Errno = 1117
	ERROR_SERIAL_NO_DEVICE                                        syscall.Errno = 1118
	ERROR_IRQ_BUSY                                                syscall.Errno = 1119
	ERROR_MORE_WRITES                                             syscall.Errno = 1120
	ERROR_COUNTER_TIMEOUT                                         syscall.Errno = 1121
	ERROR_FLOPPY_ID_MARK_NOT_FOUND                                syscall.Errno = 1122
	ERROR_FLOPPY_WRONG_CYLINDER                                   syscall.Errno = 1123
	ERROR_FLOPPY_UNKNOWN_ERROR                                    syscall.Errno = 1124
	ERROR_FLOPPY_BAD_REGISTERS                                    syscall.Errno = 1125
	ERROR_DISK_RECALIBRATE_FAILED                                 syscall.Errno = 1126
	ERROR_DISK_OPERATION_FAILED                                   syscall.Errno = 1127
	ERROR_DISK_RESET_FAILED                                       syscall.Errno = 1128
	ERROR_EOM_OVERFLOW                                            syscall.Errno = 1129
	ERROR_NOT_ENOUGH_SERVER_MEMORY                                syscall.Errno = 1130
	ERROR_POSSIBLE_DEADLOCK                                       syscall.Errno = 1131
	ERROR_MAPPED_ALIGNMENT                                        syscall.Errno = 1132
	ERROR_SET_POWER_STATE_VETOED                                  syscall.Errno = 1140
	ERROR_SET_POWER_STATE_FAILED                                  syscall.Errno = 1141
	ERROR_TOO_MANY_LINKS                                          syscall.Errno = 1142
	ERROR_OLD_WIN_VERSION                                         syscall.Errno = 1150
	ERROR_APP_WRONG_OS                                            syscall.Errno = 1151
	ERROR_SINGLE_INSTANCE_APP                                     syscall.Errno = 1152
	ERROR_RMODE_APP                                               syscall.Errno = 1153
	ERROR_INVALID_DLL                                             syscall.Errno = 1154
	ERROR_NO_ASSOCIATION                                          syscall.Errno = 1155
	ERROR_DDE_FAIL                                                syscall.Errno = 1156
	ERROR_DLL_NOT_FOUND                                           syscall.Errno = 1157
	ERROR_NO_MORE_USER_HANDLES                                    syscall.Errno = 1158
	ERROR_MESSAGE_SYNC_ONLY                                       syscall.Errno = 1159
	ERROR_SOURCE_ELEMENT_EMPTY                                    syscall.Errno = 1160
	ERROR_DESTINATION_ELEMENT_FULL                                syscall.Errno = 1161
	ERROR_ILLEGAL_ELEMENT_ADDRESS                                 syscall.Errno = 1162
	ERROR_MAGAZINE_NOT_PRESENT                                    syscall.Errno = 1163
	ERROR_DEVICE_REINITIALIZATION_NEEDED                          syscall.Errno = 1164
	ERROR_DEVICE_REQUIRES_CLEANING                                syscall.Errno = 1165
	ERROR_DEVICE_DOOR_OPEN                                        syscall.Errno = 1166
	ERROR_DEVICE_NOT_CONNECTED                                    syscall.Errno = 1167
	ERROR_NOT_FOUND                                               syscall.Errno = 1168
	ERROR_NO_MATCH                                                syscall.Errno = 1169
	ERROR_SET_NOT_FOUND                                           syscall.Errno = 1170
	ERROR_POINT_NOT_FOUND                                         syscall.Errno = 1171
	ERROR_NO_TRACKING_SERVICE                                     syscall.Errno = 1172
	ERROR_NO_VOLUME_ID                                            syscall.Errno = 1173
	ERROR_UNABLE_TO_REMOVE_REPLACED                               syscall.Errno = 1175
	ERROR_UNABLE_TO_MOVE_REPLACEMENT                              syscall.Errno = 1176
	ERROR_UNABLE_TO_MOVE_REPLACEMENT_2                            syscall.Errno = 1177
	ERROR_JOURNAL_DELETE_IN_PROGRESS                              syscall.Errno = 1178
	ERROR_JOURNAL_NOT_ACTIVE                                      syscall.Errno = 1179
	ERROR_POTENTIAL_FILE_FOUND                                    syscall.Errno = 1180
	ERROR_JOURNAL_ENTRY_DELETED                                   syscall.Errno = 1181
	ERROR_SHUTDOWN_IS_SCHEDULED                                   syscall.Errno = 1190
	ERROR_SHUTDOWN_USERS_LOGGED_ON                                syscall.Errno = 1191
	ERROR_BAD_DEVICE                                              syscall.Errno = 1200
	ERROR_CONNECTION_UNAVAIL                                      syscall.Errno = 1201
	ERROR_DEVICE_ALREADY_REMEMBERED                               syscall.Errno = 1202
	ERROR_NO_NET_OR_BAD_PATH                                      syscall.Errno = 1203
	ERROR_BAD_PROVIDER                                            syscall.Errno = 1204
	ERROR_CANNOT_OPEN_PROFILE                                     syscall.Errno = 1205
	ERROR_BAD_PROFILE                                             syscall.Errno = 1206
	ERROR_NOT_CONTAINER                                           syscall.Errno = 1207
	ERROR_EXTENDED_ERROR                                          syscall.Errno = 1208
	ERROR_INVALID_GROUPNAME                                       syscall.Errno = 1209
	ERROR_INVALID_COMPUTERNAME                                    syscall.Errno = 1210
	ERROR_INVALID_EVENTNAME                                       syscall.Errno = 1211
	ERROR_INVALID_DOMAINNAME                                      syscall.Errno = 1212
	ERROR_INVALID_SERVICENAME                                     syscall.Errno = 1213
	ERROR_INVALID_NETNAME                                         syscall.Errno = 1214
	ERROR_INVALID_SHARENAME                                       syscall.Errno = 1215
	ERROR_INVALID_PASSWORDNAME                                    syscall.Errno = 1216
	ERROR_INVALID_MESSAGENAME                                     syscall.Errno = 1217
	ERROR_INVALID_MESSAGEDEST                                     syscall.Errno = 1218
	ERROR_SESSION_CREDENTIAL_CONFLICT                             syscall.Errno = 1219
	ERROR_REMOTE_SESSION_LIMIT_EXCEEDED                           syscall.Errno = 1220
	ERROR_DUP_DOMAINNAME                                          syscall.Errno = 1221
	ERROR_NO_NETWORK                                              syscall.Errno = 1222
	ERROR_CANCELLED                                               syscall.Errno = 1223
	ERROR_USER_MAPPED_FILE                                        syscall.Errno = 1224
	ERROR_CONNECTION_REFUSED                                      syscall.Errno = 1225
	ERROR_GRACEFUL_DISCONNECT                                     syscall.Errno = 1226
	ERROR_ADDRESS_ALREADY_ASSOCIATED                              syscall.Errno = 1227
	ERROR_ADDRESS_NOT_ASSOCIATED                                  syscall.Errno = 1228
	ERROR_CONNECTION_INVALID                                      syscall.Errno = 1229
	ERROR_CONNECTION_ACTIVE                                       syscall.Errno = 1230
	ERROR_NETWORK_UNREACHABLE                                     syscall.Errno = 1231
	ERROR_HOST_UNREACHABLE                                        syscall.Errno = 1232
	ERROR_PROTOCOL_UNREACHABLE                                    syscall.Errno = 1233
	ERROR_PORT_UNREACHABLE                                        syscall.Errno = 1234
	ERROR_REQUEST_ABORTED                                         syscall.Errno = 1235
	ERROR_CONNECTION_ABORTED                                      syscall.Errno = 1236
	ERROR_RETRY                                                   syscall.Errno = 1237
	ERROR_CONNECTION_COUNT_LIMIT                                  syscall.Errno = 1238
	ERROR_LOGIN_TIME_RESTRICTION                                  syscall.Errno = 1239
	ERROR_LOGIN_WKSTA_RESTRICTION                                 syscall.Errno = 1240
	ERROR_INCORRECT_ADDRESS                                       syscall.Errno = 1241
	ERROR_ALREADY_REGISTERED                                      syscall.Errno = 1242
	ERROR_SERVICE_NOT_FOUND                                       syscall.Errno = 1243
	ERROR_NOT_AUTHENTICATED                                       syscall.Errno = 1244
	ERROR_NOT_LOGGED_ON                                           syscall.Errno = 1245
	ERROR_CONTINUE                                                syscall.Errno = 1246
	ERROR_ALREADY_INITIALIZED                                     syscall.Errno = 1247
	ERROR_NO_MORE_DEVICES                                         syscall.Errno = 1248
	ERROR_NO_SUCH_SITE                                            syscall.Errno = 1249
	ERROR_DOMAIN_CONTROLLER_EXISTS                                syscall.Errno = 1250
	ERROR_ONLY_IF_CONNECTED                                       syscall.Errno = 1251
	ERROR_OVERRIDE_NOCHANGES                                      syscall.Errno = 1252
	ERROR_BAD_USER_PROFILE                                        syscall.Errno = 1253
	ERROR_NOT_SUPPORTED_ON_SBS                                    syscall.Errno = 1254
	ERROR_SERVER_SHUTDOWN_IN_PROGRESS                             syscall.Errno = 1255
	ERROR_HOST_DOWN                                               syscall.Errno = 1256
	ERROR_NON_ACCOUNT_SID                                         syscall.Errno = 1257
	ERROR_NON_DOMAIN_SID                                          syscall.Errno = 1258
	ERROR_APPHELP_BLOCK                                           syscall.Errno = 1259
	ERROR_ACCESS_DISABLED_BY_POLICY                               syscall.Errno = 1260
	ERROR_REG_NAT_CONSUMPTION                                     syscall.Errno = 1261
	ERROR_CSCSHARE_OFFLINE                                        syscall.Errno = 1262
	ERROR_PKINIT_FAILURE                                          syscall.Errno = 1263
	ERROR_SMARTCARD_SUBSYSTEM_FAILURE                             syscall.Errno = 1264
	ERROR_DOWNGRADE_DETECTED                                      syscall.Errno = 1265
	ERROR_MACHINE_LOCKED                                          syscall.Errno = 1271
	ERROR_CALLBACK_SUPPLIED_INVALID_DATA                          syscall.Errno = 1273
	ERROR_SYNC_FOREGROUND_REFRESH_REQUIRED                        syscall.Errno = 1274
	ERROR_DRIVER_BLOCKED                                          syscall.Errno = 1275
	ERROR_INVALID_IMPORT_OF_NON_DLL                               syscall.Errno = 1276
	ERROR_ACCESS_DISABLED_WEBBLADE                                syscall.Errno = 1277
	ERROR_ACCESS_DISABLED_WEBBLADE_TAMPER                         syscall.Errno = 1278
	ERROR_RECOVERY_FAILURE                                        syscall.Errno = 1279
	ERROR_ALREADY_FIBER                                           syscall.Errno = 1280
	ERROR_ALREADY_THREAD                                          syscall.Errno = 1281
	ERROR_STACK_BUFFER_OVERRUN                                    syscall.Errno = 1282
	ERROR_PARAMETER_QUOTA_EXCEEDED                                syscall.Errno = 1283
	ERROR_DEBUGGER_INACTIVE                                       syscall.Errno = 1284
	ERROR_DELAY_LOAD_FAILED                                       syscall.Errno = 1285
	ERROR_VDM_DISALLOWED                                          syscall.Errno = 1286
	ERROR_UNIDENTIFIED_ERROR                                      syscall.Errno = 1287
	ERROR_INVALID_CRUNTIME_PARAMETER                              syscall.Errno = 1288
	ERROR_BEYOND_VDL                                              syscall.Errno = 1289
	ERROR_INCOMPATIBLE_SERVICE_SID_TYPE                           syscall.Errno = 1290
	ERROR_DRIVER_PROCESS_TERMINATED                               syscall.Errno = 1291
	ERROR_IMPLEMENTATION_LIMIT                                    syscall.Errno = 1292
	ERROR_PROCESS_IS_PROTECTED                                    syscall.Errno = 1293
	ERROR_SERVICE_NOTIFY_CLIENT_LAGGING                           syscall.Errno = 1294
	ERROR_DISK_QUOTA_EXCEEDED                                     syscall.Errno = 1295
	ERROR_CONTENT_BLOCKED                                         syscall.Errno = 1296
	ERROR_INCOMPATIBLE_SERVICE_PRIVILEGE                          syscall.Errno = 1297
	ERROR_APP_HANG                                                syscall.Errno = 1298
)

const (
	ERROR_INVALID_LABEL                syscall.Errno = 1299
	ERROR_NOT_ALL_ASSIGNED             syscall.Errno = 1300
	ERROR_SOME_NOT_MAPPED              syscall.Errno = 1301
	ERROR_NO_QUOTAS_FOR_ACCOUNT        syscall.Errno = 1302
	ERROR_LOCAL_USER_SESSION_KEY       syscall.Errno = 1303
	ERROR_NULL_LM_PASSWORD             syscall.Errno = 1304
	ERROR_UNKNOWN_REVISION             syscall.Errno = 1305
	ERROR_REVISION_MISMATCH            syscall.Errno = 1306
	ERROR_INVALID_OWNER                syscall.Errno = 1307
	ERROR_INVALID_PRIMARY_GROUP        syscall.Errno = 1308
	ERROR_NO_IMPERSONATION_TOKEN       syscall.Errno = 1309
	ERROR_CANT_DISABLE_MANDATORY       syscall.Errno = 1310
	ERROR_NO_LOGON_SERVERS             syscall.Errno = 1311
	ERROR_NO_SUCH_LOGON_SESSION        syscall.Errno = 1312
	ERROR_NO_SUCH_PRIVILEGE            syscall.Errno = 1313
	ERROR_PRIVILEGE_NOT_HELD           syscall.Errno = 1314
	ERROR_INVALID_ACCOUNT_NAME         syscall.Errno = 1315
	ERROR_USER_EXISTS                  syscall.Errno = 1316
	ERROR_NO_SUCH_USER                 syscall.Errno = 1317
	ERROR_GROUP_EXISTS                 syscall.Errno = 1318
	ERROR_NO_SUCH_GROUP                syscall.Errno = 1319
	ERROR_MEMBER_IN_GROUP              syscall.Errno = 1320
	ERROR_MEMBER_NOT_IN_GROUP          syscall.Errno = 1321
	ERROR_LAST_ADMIN                   syscall.Errno = 1322
	ERROR_WRONG_PASSWORD               syscall.Errno = 1323
	ERROR_ILL_FORMED_PASSWORD          syscall.Errno = 1324
	ERROR_PASSWORD_RESTRICTION         syscall.Errno = 1325
	ERROR_LOGON_FAILURE                syscall.Errno = 1326
	ERROR_ACCOUNT_RESTRICTION          syscall.Errno = 1327
	ERROR_INVALID_LOGON_HOURS          syscall.Errno = 1328
	ERROR_INVALID_WORKSTATION          syscall.Errno = 1329
	ERROR_PASSWORD_EXPIRED             syscall.Errno = 1330
	ERROR_ACCOUNT_DISABLED             syscall.Errno = 1331
	ERROR_NONE_MAPPED                  syscall.Errno = 1332
	ERROR_TOO_MANY_LUIDS_REQUESTED     syscall.Errno = 1333
	ERROR_LUIDS_EXHAUSTED              syscall.Errno = 1334
	ERROR_INVALID_SUB_AUTHORITY        syscall.Errno = 1335
	ERROR_INVALID_ACL                  syscall.Errno = 1336
	ERROR_INVALID_SID                  syscall.Errno = 1337
	ERROR_INVALID_SECURITY_DESCR       syscall.Errno = 1338
	ERROR_BAD_INHERITANCE_ACL          syscall.Errno = 1340
	ERROR_SERVER_DISABLED              syscall.Errno = 1341
	ERROR_SERVER_NOT_DISABLED          syscall.Errno = 1342
	ERROR_INVALID_ID_AUTHORITY         syscall.Errno = 1343
	ERROR_ALLOTTED_SPACE_EXCEEDED      syscall.Errno = 1344
	ERROR_INVALID_GROUP_ATTRIBUTES     syscall.Errno = 1345
	ERROR_BAD_IMPERSONATION_LEVEL      syscall.Errno = 1346
	ERROR_CANT_OPEN_ANONYMOUS          syscall.Errno = 1347
	ERROR_BAD_VALIDATION_CLASS         syscall.Errno = 1348
	ERROR_BAD_TOKEN_TYPE               syscall.Errno = 1349
	ERROR_NO_SECURITY_ON_OBJECT        syscall.Errno = 1350
	ERROR_CANT_ACCESS_DOMAIN_INFO      syscall.Errno = 1351
	ERROR_INVALID_SERVER_STATE         syscall.Errno = 1352
	ERROR_INVALID_DOMAIN_STATE         syscall.Errno = 1353
	ERROR_INVALID_DOMAIN_ROLE          syscall.Errno = 1354
	ERROR_NO_SUCH_DOMAIN               syscall.Errno = 1355
	ERROR_DOMAIN_EXISTS                syscall.Errno = 1356
	ERROR_DOMAIN_LIMIT_EXCEEDED        syscall.Errno = 1357
	ERROR_INTERNAL_DB_CORRUPTION       syscall.Errno = 1358
	ERROR_INTERNAL_ERROR               syscall.Errno = 1359
	ERROR_GENERIC_NOT_MAPPED           syscall.Errno = 1360
	ERROR_BAD_DESCRIPTOR_FORMAT        syscall.Errno = 1361
	ERROR_NOT_LOGON_PROCESS            syscall.Errno = 1362
	ERROR_LOGON_SESSION_EXISTS         syscall.Errno = 1363
	ERROR_NO_SUCH_PACKAGE              syscall.Errno = 1364
	ERROR_BAD_LOGON_SESSION_STATE      syscall.Errno = 1365
	ERROR_LOGON_SESSION_COLLISION      syscall.Errno = 1366
	ERROR_INVALID_LOGON_TYPE           syscall.Errno = 1367
	ERROR_CANNOT_IMPERSONATE           syscall.Errno = 1368
	ERROR_RXACT_INVALID_STATE          syscall.Errno = 1369
	ERROR_RXACT_COMMIT_FAILURE         syscall.Errno = 1370
	ERROR_SPECIAL_ACCOUNT              syscall.Errno = 1371
	ERROR_SPECIAL_GROUP                syscall.Errno = 1372
	ERROR_SPECIAL_USER                 syscall.Errno = 1373
	ERROR_MEMBERS_PRIMARY_GROUP        syscall.Errno = 1374
	ERROR_TOKEN_ALREADY_IN_USE         syscall.Errno = 1375
	ERROR_NO_SUCH_ALIAS                syscall.Errno = 1376
	ERROR_MEMBER_NOT_IN_ALIAS          syscall.Errno = 1377
	ERROR_MEMBER_IN_ALIAS              syscall.Errno = 1378
	ERROR_ALIAS_EXISTS                 syscall.Errno = 1379
	ERROR_LOGON_NOT_GRANTED            syscall.Errno = 1380
	ERROR_TOO_MANY_SECRETS             syscall.Errno = 1381
	ERROR_SECRET_TOO_LONG              syscall.Errno = 1382
	ERROR_INTERNAL_DB_ERROR            syscall.Errno = 1383
	ERROR_TOO_MANY_CONTEXT_IDS         syscall.Errno = 1384
	ERROR_LOGON_TYPE_NOT_GRANTED       syscall.Errno = 1385
	ERROR_NT_CROSS_ENCRYPTION_REQUIRED syscall.Errno = 1386
	ERROR_NO_SUCH_MEMBER               syscall.Errno = 1387
	ERROR_INVALID_MEMBER               syscall.Errno = 1388
	ERROR_TOO_MANY_SIDS                syscall.Errno = 1389
	ERROR_LM_CROSS_ENCRYPTION_REQUIRED syscall.Errno = 1390
	ERROR_NO_INHERITANCE               syscall.Errno = 1391
	ERROR_FILE_CORRUPT                 syscall.Errno = 1392
	ERROR_DISK_CORRUPT                 syscall.Errno = 1393
	ERROR_NO_USER_SESSION_KEY          syscall.Errno = 1394
	ERROR_LICENSE_QUOTA_EXCEEDED       syscall.Errno = 1395
	ERROR_WRONG_TARGET_NAME            syscall.Errno = 1396
	ERROR_MUTUAL_AUTH_FAILED           syscall.Errno = 1397
	ERROR_TIME_SKEW                    syscall.Errno = 1398
	ERROR_CURRENT_DOMAIN_NOT_ALLOWED   syscall.Errno = 1399
)

const (
	ERROR_EVENTLOG_FILE_CORRUPT syscall.Errno = 1500
	ERROR_EVENTLOG_CANT_START   syscall.Errno = 1501
	ERROR_EVENTLOG_FILE_FULL    syscall.Errno = 1502
	ERROR_EVENTLOG_FILE_CHANGED syscall.Errno = 1503
)

const (
	ERROR_INSTALL_SERVICE_FAILURE           syscall.Errno = 1601
	ERROR_INSTALL_USEREXIT                  syscall.Errno = 1602
	ERROR_INSTALL_FAILURE                   syscall.Errno = 1603
	ERROR_INSTALL_SUSPEND                   syscall.Errno = 1604
	ERROR_UNKNOWN_PRODUCT                   syscall.Errno = 1605
	ERROR_UNKNOWN_FEATURE                   syscall.Errno = 1606
	ERROR_UNKNOWN_COMPONENT                 syscall.Errno = 1607
	ERROR_UNKNOWN_PROPERTY                  syscall.Errno = 1608
	ERROR_INVALID_HANDLE_STATE              syscall.Errno = 1609
	ERROR_BAD_CONFIGURATION                 syscall.Errno = 1610
	ERROR_INDEX_ABSENT                      syscall.Errno = 1611
	ERROR_INSTALL_SOURCE_ABSENT             syscall.Errno = 1612
	ERROR_INSTALL_PACKAGE_VERSION           syscall.Errno = 1613
	ERROR_PRODUCT_UNINSTALLED               syscall.Errno = 1614
	ERROR_BAD_QUERY_SYNTAX                  syscall.Errno = 1615
	ERROR_INVALID_FIELD                     syscall.Errno = 1616
	ERROR_DEVICE_REMOVED                    syscall.Errno = 1617
	ERROR_INSTALL_ALREADY_RUNNING           syscall.Errno = 1618
	ERROR_INSTALL_PACKAGE_OPEN_FAILED       syscall.Errno = 1619
	ERROR_INSTALL_PACKAGE_INVALID           syscall.Errno = 1620
	ERROR_INSTALL_UI_FAILURE                syscall.Errno = 1621
	ERROR_INSTALL_LOG_FAILURE               syscall.Errno = 1622
	ERROR_INSTALL_LANGUAGE_UNSUPPORTED      syscall.Errno = 1623
	ERROR_INSTALL_TRANSFORM_FAILURE         syscall.Errno = 1624
	ERROR_INSTALL_PACKAGE_REJECTED          syscall.Errno = 1625
	ERROR_FUNCTION_NOT_CALLED               syscall.Errno = 1626
	ERROR_FUNCTION_FAILED                   syscall.Errno = 1627
	ERROR_INVALID_TABLE                     syscall.Errno = 1628
	ERROR_DATATYPE_MISMATCH                 syscall.Errno = 1629
	ERROR_UNSUPPORTED_TYPE                  syscall.Errno = 1630
	ERROR_CREATE_FAILED                     syscall.Errno = 1631
	ERROR_INSTALL_TEMP_UNWRITABLE           syscall.Errno = 1632
	ERROR_INSTALL_PLATFORM_UNSUPPORTED      syscall.Errno = 1633
	ERROR_INSTALL_NOTUSED                   syscall.Errno = 1634
	ERROR_PATCH_PACKAGE_OPEN_FAILED         syscall.Errno = 1635
	ERROR_PATCH_PACKAGE_INVALID             syscall.Errno = 1636
	ERROR_PATCH_PACKAGE_UNSUPPORTED         syscall.Errno = 1637
	ERROR_PRODUCT_VERSION                   syscall.Errno = 1638
	ERROR_INVALID_COMMAND_LINE              syscall.Errno = 1639
	ERROR_INSTALL_REMOTE_DISALLOWED         syscall.Errno = 1640
	ERROR_SUCCESS_REBOOT_INITIATED          syscall.Errno = 1641
	ERROR_PATCH_TARGET_NOT_FOUND            syscall.Errno = 1642
	ERROR_PATCH_PACKAGE_REJECTED            syscall.Errno = 1643
	ERROR_INSTALL_TRANSFORM_REJECTED        syscall.Errno = 1644
	ERROR_INSTALL_REMOTE_PROHIBITED         syscall.Errno = 1645
	ERROR_PATCH_REMOVAL_UNSUPPORTED         syscall.Errno = 1646
	ERROR_UNKNOWN_PATCH                     syscall.Errno = 1647
	ERROR_PATCH_NO_SEQUENCE                 syscall.Errno = 1648
	ERROR_PATCH_REMOVAL_DISALLOWED          syscall.Errno = 1649
	ERROR_INVALID_PATCH_XML                 syscall.Errno = 1650
	ERROR_PATCH_MANAGED_ADVERTISTED_PRODUCT syscall.Errno = 1651
	ERROR_INSTALL_SERVICE_SAFEBOOT          syscall.Errno = 1652
	ERROR_FAIL_FAST_EXCEPTION               syscall.Errno = 1653
)

const (
	SEVERITY_SUCCESS = 0
	SEVERITY_ERROR   = 1
)

func SUCCEEDED(hr uint32) bool {
	return int32(hr) >= 0
}

func FAILED(hr uint32) bool {
	return int32(hr) < 0
}

func HRESULT_CODE(hr uint32) uint16 {
	return uint16(hr)
}

func HRESULT_FACILITY(hr uint32) uint16 {
	return uint16((hr >> 16) & 0x1FFF)
}

func HRESULT_SEVERITY(hr uint32) uint32 {
	return hr >> 31
}

const (
	E_UNEXPECTED                                  = 0x8000FFFF
	E_NOTIMPL                                     = 0x80004001
	E_OUTOFMEMORY                                 = 0x8007000E
	E_INVALIDARG                                  = 0x80070057
	E_NOINTERFACE                                 = 0x80004002
	E_POINTER                                     = 0x80004003
	E_HANDLE                                      = 0x80070006
	E_ABORT                                       = 0x80004004
	E_FAIL                                        = 0x80004005
	E_ACCESSDENIED                                = 0x80070005
	E_PENDING                                     = 0x8000000A
	CO_E_INIT_TLS                                 = 0x80004006
	CO_E_INIT_SHARED_ALLOCATOR                    = 0x80004007
	CO_E_INIT_MEMORY_ALLOCATOR                    = 0x80004008
	CO_E_INIT_CLASS_CACHE                         = 0x80004009
	CO_E_INIT_RPC_CHANNEL                         = 0x8000400A
	CO_E_INIT_TLS_SET_CHANNEL_CONTROL             = 0x8000400B
	CO_E_INIT_TLS_CHANNEL_CONTROL                 = 0x8000400C
	CO_E_INIT_UNACCEPTED_USER_ALLOCATOR           = 0x8000400D
	CO_E_INIT_SCM_MUTEX_EXISTS                    = 0x8000400E
	CO_E_INIT_SCM_FILE_MAPPING_EXISTS             = 0x8000400F
	CO_E_INIT_SCM_MAP_VIEW_OF_FILE                = 0x80004010
	CO_E_INIT_SCM_EXEC_FAILURE                    = 0x80004011
	CO_E_INIT_ONLY_SINGLE_THREADED                = 0x80004012
	CO_E_INIT_CANT_REMOTE                         = 0x80004013
	CO_E_BAD_SERVER_NAME                          = 0x80004014
	CO_E_WRONG_SERVER_IDENTITY                    = 0x80004015
	CO_E_OLE1DDE_DISABLED                         = 0x80004016
	CO_E_RUNAS_SYNTAX                             = 0x80004017
	CO_E_CREATEPROCESS_FAILURE                    = 0x80004018
	CO_E_RUNAS_CREATEPROCESS_FAILURE              = 0x80004019
	CO_E_RUNAS_LOGON_FAILURE                      = 0x8000401A
	CO_E_LAUNCH_PERMISSION_DENIED                 = 0x8000401B
	CO_E_START_SERVICE_FAILURE                    = 0x8000401C
	CO_E_REMOTE_COMMUNICATION_FAILURE             = 0x8000401D
	CO_E_SERVER_START_TIMEOUT                     = 0x8000401E
	CO_E_CLSREG_INCONSISTENT                      = 0x8000401F
	CO_E_IIDREG_INCONSISTENT                      = 0x80004020
	CO_E_NOT_SUPPORTED                            = 0x80004021
	CO_E_RELOAD_DLL                               = 0x80004022
	CO_E_MSI_ERROR                                = 0x80004023
	CO_E_ATTEMPT_TO_CREATE_OUTSIDE_CLIENT_CONTEXT = 0x80004024
	CO_E_SERVER_PAUSED                            = 0x80004025
	CO_E_SERVER_NOT_PAUSED                        = 0x80004026
	CO_E_CLASS_DISABLED                           = 0x80004027
	CO_E_CLRNOTAVAILABLE                          = 0x80004028
	CO_E_ASYNC_WORK_REJECTED                      = 0x80004029
	CO_E_SERVER_INIT_TIMEOUT                      = 0x8000402A
	CO_E_NO_SECCTX_IN_ACTIVATE                    = 0x8000402B
	CO_E_TRACKER_CONFIG                           = 0x80004030
	CO_E_THREADPOOL_CONFIG                        = 0x80004031
	CO_E_SXS_CONFIG                               = 0x80004032
	CO_E_MALFORMED_SPN                            = 0x80004033
)

const (
	S_OK    = 0
	S_FALSE = 1
)

const (
	OLE_E_OLEVERB                                     = 0x80040000
	OLE_E_ADVF                                        = 0x80040001
	OLE_E_ENUM_NOMORE                                 = 0x80040002
	OLE_E_ADVISENOTSUPPORTED                          = 0x80040003
	OLE_E_NOCONNECTION                                = 0x80040004
	OLE_E_NOTRUNNING                                  = 0x80040005
	OLE_E_NOCACHE                                     = 0x80040006
	OLE_E_BLANK                                       = 0x80040007
	OLE_E_CLASSDIFF                                   = 0x80040008
	OLE_E_CANT_GETMONIKER                             = 0x80040009
	OLE_E_CANT_BINDTOSOURCE                           = 0x8004000A
	OLE_E_STATIC                                      = 0x8004000B
	OLE_E_PROMPTSAVECANCELLED                         = 0x8004000C
	OLE_E_INVALIDRECT                                 = 0x8004000D
	OLE_E_WRONGCOMPOBJ                                = 0x8004000E
	OLE_E_INVALIDHWND                                 = 0x8004000F
	OLE_E_NOT_INPLACEACTIVE                           = 0x80040010
	OLE_E_CANTCONVERT                                 = 0x80040011
	OLE_E_NOSTORAGE                                   = 0x80040012
	DV_E_FORMATETC                                    = 0x80040064
	DV_E_DVTARGETDEVICE                               = 0x80040065
	DV_E_STGMEDIUM                                    = 0x80040066
	DV_E_STATDATA                                     = 0x80040067
	DV_E_LINDEX                                       = 0x80040068
	DV_E_TYMED                                        = 0x80040069
	DV_E_CLIPFORMAT                                   = 0x8004006A
	DV_E_DVASPECT                                     = 0x8004006B
	DV_E_DVTARGETDEVICE_SIZE                          = 0x8004006C
	DV_E_NOIVIEWOBJECT                                = 0x8004006D
	DRAGDROP_E_NOTREGISTERED                          = 0x80040100
	DRAGDROP_E_ALREADYREGISTERED                      = 0x80040101
	DRAGDROP_E_INVALIDHWND                            = 0x80040102
	CLASS_E_NOAGGREGATION                             = 0x80040110
	CLASS_E_CLASSNOTAVAILABLE                         = 0x80040111
	CLASS_E_NOTLICENSED                               = 0x80040112
	VIEW_E_DRAW                                       = 0x80040140
	REGDB_E_READREGDB                                 = 0x80040150
	REGDB_E_WRITEREGDB                                = 0x80040151
	REGDB_E_KEYMISSING                                = 0x80040152
	REGDB_E_INVALIDVALUE                              = 0x80040153
	REGDB_E_CLASSNOTREG                               = 0x80040154
	REGDB_E_IIDNOTREG                                 = 0x80040155
	REGDB_E_BADTHREADINGMODEL                         = 0x80040156
	CAT_E_CATIDNOEXIST                                = 0x80040160
	CAT_E_NODESCRIPTION                               = 0x80040161
	CS_E_PACKAGE_NOTFOUND                             = 0x80040164
	CS_E_NOT_DELETABLE                                = 0x80040165
	CS_E_CLASS_NOTFOUND                               = 0x80040166
	CS_E_INVALID_VERSION                              = 0x80040167
	CS_E_NO_CLASSSTORE                                = 0x80040168
	CS_E_OBJECT_NOTFOUND                              = 0x80040169
	CS_E_OBJECT_ALREADY_EXISTS                        = 0x8004016A
	CS_E_INVALID_PATH                                 = 0x8004016B
	CS_E_NETWORK_ERROR                                = 0x8004016C
	CS_E_ADMIN_LIMIT_EXCEEDED                         = 0x8004016D
	CS_E_SCHEMA_MISMATCH                              = 0x8004016E
	CS_E_INTERNAL_ERROR                               = 0x8004016F
	CACHE_E_NOCACHE_UPDATED                           = 0x80040170
	OLEOBJ_E_NOVERBS                                  = 0x80040180
	OLEOBJ_E_INVALIDVERB                              = 0x80040181
	INPLACE_E_NOTUNDOABLE                             = 0x800401A0
	INPLACE_E_NOTOOLSPACE                             = 0x800401A1
	CONVERT10_E_OLESTREAM_GET                         = 0x800401C0
	CONVERT10_E_OLESTREAM_PUT                         = 0x800401C1
	CONVERT10_E_OLESTREAM_FMT                         = 0x800401C2
	CONVERT10_E_OLESTREAM_BITMAP_TO_DIB               = 0x800401C3
	CONVERT10_E_STG_FMT                               = 0x800401C4
	CONVERT10_E_STG_NO_STD_STREAM                     = 0x800401C5
	CONVERT10_E_STG_DIB_TO_BITMAP                     = 0x800401C6
	CLIPBRD_E_CANT_OPEN                               = 0x800401D0
	CLIPBRD_E_CANT_EMPTY                              = 0x800401D1
	CLIPBRD_E_CANT_SET                                = 0x800401D2
	CLIPBRD_E_BAD_DATA                                = 0x800401D3
	CLIPBRD_E_CANT_CLOSE                              = 0x800401D4
	MK_E_CONNECTMANUALLY                              = 0x800401E0
	MK_E_EXCEEDEDDEADLINE                             = 0x800401E1
	MK_E_NEEDGENERIC                                  = 0x800401E2
	MK_E_UNAVAILABLE                                  = 0x800401E3
	MK_E_SYNTAX                                       = 0x800401E4
	MK_E_NOOBJECT                                     = 0x800401E5
	MK_E_INVALIDEXTENSION                             = 0x800401E6
	MK_E_INTERMEDIATEINTERFACENOTSUPPORTED            = 0x800401E7
	MK_E_NOTBINDABLE                                  = 0x800401E8
	MK_E_NOTBOUND                                     = 0x800401E9
	MK_E_CANTOPENFILE                                 = 0x800401EA
	MK_E_MUSTBOTHERUSER                               = 0x800401EB
	MK_E_NOINVERSE                                    = 0x800401EC
	MK_E_NOSTORAGE                                    = 0x800401ED
	MK_E_NOPREFIX                                     = 0x800401EE
	MK_E_ENUMERATION_FAILED                           = 0x800401EF
	CO_E_NOTINITIALIZED                               = 0x800401F0
	CO_E_ALREADYINITIALIZED                           = 0x800401F1
	CO_E_CANTDETERMINECLASS                           = 0x800401F2
	CO_E_CLASSSTRING                                  = 0x800401F3
	CO_E_IIDSTRING                                    = 0x800401F4
	CO_E_APPNOTFOUND                                  = 0x800401F5
	CO_E_APPSINGLEUSE                                 = 0x800401F6
	CO_E_ERRORINAPP                                   = 0x800401F7
	CO_E_DLLNOTFOUND                                  = 0x800401F8
	CO_E_ERRORINDLL                                   = 0x800401F9
	CO_E_WRONGOSFORAPP                                = 0x800401FA
	CO_E_OBJNOTREG                                    = 0x800401FB
	CO_E_OBJISREG                                     = 0x800401FC
	CO_E_OBJNOTCONNECTED                              = 0x800401FD
	CO_E_APPDIDNTREG                                  = 0x800401FE
	CO_E_RELEASED                                     = 0x800401FF
	EVENT_S_SOME_SUBSCRIBERS_FAILED                   = 0x00040200
	EVENT_E_ALL_SUBSCRIBERS_FAILED                    = 0x80040201
	EVENT_S_NOSUBSCRIBERS                             = 0x00040202
	EVENT_E_QUERYSYNTAX                               = 0x80040203
	EVENT_E_QUERYFIELD                                = 0x80040204
	EVENT_E_INTERNALEXCEPTION                         = 0x80040205
	EVENT_E_INTERNALERROR                             = 0x80040206
	EVENT_E_INVALID_PER_USER_SID                      = 0x80040207
	EVENT_E_USER_EXCEPTION                            = 0x80040208
	EVENT_E_TOO_MANY_METHODS                          = 0x80040209
	EVENT_E_MISSING_EVENTCLASS                        = 0x8004020A
	EVENT_E_NOT_ALL_REMOVED                           = 0x8004020B
	EVENT_E_COMPLUS_NOT_INSTALLED                     = 0x8004020C
	EVENT_E_CANT_MODIFY_OR_DELETE_UNCONFIGURED_OBJECT = 0x8004020D
	EVENT_E_CANT_MODIFY_OR_DELETE_CONFIGURED_OBJECT   = 0x8004020E
	EVENT_E_INVALID_EVENT_CLASS_PARTITION             = 0x8004020F
	EVENT_E_PER_USER_SID_NOT_LOGGED_ON                = 0x80040210
	XACT_E_ALREADYOTHERSINGLEPHASE                    = 0x8004D000
	XACT_E_CANTRETAIN                                 = 0x8004D001
	XACT_E_COMMITFAILED                               = 0x8004D002
	XACT_E_COMMITPREVENTED                            = 0x8004D003
	XACT_E_HEURISTICABORT                             = 0x8004D004
	XACT_E_HEURISTICCOMMIT                            = 0x8004D005
	XACT_E_HEURISTICDAMAGE                            = 0x8004D006
	XACT_E_HEURISTICDANGER                            = 0x8004D007
	XACT_E_ISOLATIONLEVEL                             = 0x8004D008
	XACT_E_NOASYNC                                    = 0x8004D009
	XACT_E_NOENLIST                                   = 0x8004D00A
	XACT_E_NOISORETAIN                                = 0x8004D00B
	XACT_E_NORESOURCE                                 = 0x8004D00C
	XACT_E_NOTCURRENT                                 = 0x8004D00D
	XACT_E_NOTRANSACTION                              = 0x8004D00E
	XACT_E_NOTSUPPORTED                               = 0x8004D00F
	XACT_E_UNKNOWNRMGRID                              = 0x8004D010
	XACT_E_WRONGSTATE                                 = 0x8004D011
	XACT_E_WRONGUOW                                   = 0x8004D012
	XACT_E_XTIONEXISTS                                = 0x8004D013
	XACT_E_NOIMPORTOBJECT                             = 0x8004D014
	XACT_E_INVALIDCOOKIE                              = 0x8004D015
	XACT_E_INDOUBT                                    = 0x8004D016
	XACT_E_NOTIMEOUT                                  = 0x8004D017
	XACT_E_ALREADYINPROGRESS                          = 0x8004D018
	XACT_E_ABORTED                                    = 0x8004D019
	XACT_E_LOGFULL                                    = 0x8004D01A
	XACT_E_TMNOTAVAILABLE                             = 0x8004D01B
	XACT_E_CONNECTION_DOWN                            = 0x8004D01C
	XACT_E_CONNECTION_DENIED                          = 0x8004D01D
	XACT_E_REENLISTTIMEOUT                            = 0x8004D01E
	XACT_E_TIP_CONNECT_FAILED                         = 0x8004D01F
	XACT_E_TIP_PROTOCOL_ERROR                         = 0x8004D020
	XACT_E_TIP_PULL_FAILED                            = 0x8004D021
	XACT_E_DEST_TMNOTAVAILABLE                        = 0x8004D022
	XACT_E_TIP_DISABLED                               = 0x8004D023
	XACT_E_NETWORK_TX_DISABLED                        = 0x8004D024
	XACT_E_PARTNER_NETWORK_TX_DISABLED                = 0x8004D025
	XACT_E_XA_TX_DISABLED                             = 0x8004D026
	XACT_E_UNABLE_TO_READ_DTC_CONFIG                  = 0x8004D027
	XACT_E_UNABLE_TO_LOAD_DTC_PROXY                   = 0x8004D028
	XACT_E_ABORTING                                   = 0x8004D029
	XACT_E_PUSH_COMM_FAILURE                          = 0x8004D02A
	XACT_E_PULL_COMM_FAILURE                          = 0x8004D02B
	XACT_E_LU_TX_DISABLED                             = 0x8004D02C
	XACT_E_CLERKNOTFOUND                              = 0x8004D080
	XACT_E_CLERKEXISTS                                = 0x8004D081
	XACT_E_RECOVERYINPROGRESS                         = 0x8004D082
	XACT_E_TRANSACTIONCLOSED                          = 0x8004D083
	XACT_E_INVALIDLSN                                 = 0x8004D084
	XACT_E_REPLAYREQUEST                              = 0x8004D085
	XACT_S_ASYNC                                      = 0x0004D000
	XACT_S_DEFECT                                     = 0x0004D001
	XACT_S_READONLY                                   = 0x0004D002
	XACT_S_SOMENORETAIN                               = 0x0004D003
	XACT_S_OKINFORM                                   = 0x0004D004
	XACT_S_MADECHANGESCONTENT                         = 0x0004D005
	XACT_S_MADECHANGESINFORM                          = 0x0004D006
	XACT_S_ALLNORETAIN                                = 0x0004D007
	XACT_S_ABORTING                                   = 0x0004D008
	XACT_S_SINGLEPHASE                                = 0x0004D009
	XACT_S_LOCALLY_OK                                 = 0x0004D00A
	XACT_S_LASTRESOURCEMANAGER                        = 0x0004D010
	CONTEXT_E_ABORTED                                 = 0x8004E002
	CONTEXT_E_ABORTING                                = 0x8004E003
	CONTEXT_E_NOCONTEXT                               = 0x8004E004
	CONTEXT_E_WOULD_DEADLOCK                          = 0x8004E005
	CONTEXT_E_SYNCH_TIMEOUT                           = 0x8004E006
	CONTEXT_E_OLDREF                                  = 0x8004E007
	CONTEXT_E_ROLENOTFOUND                            = 0x8004E00C
	CONTEXT_E_TMNOTAVAILABLE                          = 0x8004E00F
	CO_E_ACTIVATIONFAILED                             = 0x8004E021
	CO_E_ACTIVATIONFAILED_EVENTLOGGED                 = 0x8004E022
	CO_E_ACTIVATIONFAILED_CATALOGERROR                = 0x8004E023
	CO_E_ACTIVATIONFAILED_TIMEOUT                     = 0x8004E024
	CO_E_INITIALIZATIONFAILED                         = 0x8004E025
	CONTEXT_E_NOJIT                                   = 0x8004E026
	CONTEXT_E_NOTRANSACTION                           = 0x8004E027
	CO_E_THREADINGMODEL_CHANGED                       = 0x8004E028
	CO_E_NOIISINTRINSICS                              = 0x8004E029
	CO_E_NOCOOKIES                                    = 0x8004E02A
	CO_E_DBERROR                                      = 0x8004E02B
	CO_E_NOTPOOLED                                    = 0x8004E02C
	CO_E_NOTCONSTRUCTED                               = 0x8004E02D
	CO_E_NOSYNCHRONIZATION                            = 0x8004E02E
	CO_E_ISOLEVELMISMATCH                             = 0x8004E02F
	CO_E_CALL_OUT_OF_TX_SCOPE_NOT_ALLOWED             = 0x8004E030
	CO_E_EXIT_TRANSACTION_SCOPE_NOT_CALLED            = 0x8004E031
	OLE_S_USEREG                                      = 0x00040000
	OLE_S_STATIC                                      = 0x00040001
	OLE_S_MAC_CLIPFORMAT                              = 0x00040002
	DRAGDROP_S_DROP                                   = 0x00040100
	DRAGDROP_S_CANCEL                                 = 0x00040101
	DRAGDROP_S_USEDEFAULTCURSORS                      = 0x00040102
	DATA_S_SAMEFORMATETC                              = 0x00040130
	VIEW_S_ALREADY_FROZEN                             = 0x00040140
	CACHE_S_FORMATETC_NOTSUPPORTED                    = 0x00040170
	CACHE_S_SAMECACHE                                 = 0x00040171
	CACHE_S_SAMECACHES_NOTUPDATED                     = 0x00040172
	OLEOBJ_S_INVALIDVERB                              = 0x00040180
	OLEOBJ_S_CANNOT_DOVERB_NOW                        = 0x00040181
	OLEOBJ_S_INVALIDHWND                              = 0x00040182
	INPLACE_S_TRUNCATED                               = 0x000401A0
	CONVERT10_S_NO_PRESENTATION                       = 0x000401C0
	MK_S_REDUCED_TO_SELF                              = 0x000401E2
	MK_S_ME                                           = 0x000401E4
	MK_S_HIM                                          = 0x000401E5
	MK_S_US                                           = 0x000401E6
	MK_S_MONIKERALREADYREGISTERED                     = 0x000401E7
	SCHED_S_TASK_READY                                = 0x00041300
	SCHED_S_TASK_RUNNING                              = 0x00041301
	SCHED_S_TASK_DISABLED                             = 0x00041302
	SCHED_S_TASK_HAS_NOT_RUN                          = 0x00041303
	SCHED_S_TASK_NO_MORE_RUNS                         = 0x00041304
	SCHED_S_TASK_NOT_SCHEDULED                        = 0x00041305
	SCHED_S_TASK_TERMINATED                           = 0x00041306
	SCHED_S_TASK_NO_VALID_TRIGGERS                    = 0x00041307
	SCHED_S_EVENT_TRIGGER                             = 0x00041308
	SCHED_E_TRIGGER_NOT_FOUND                         = 0x80041309
	SCHED_E_TASK_NOT_READY                            = 0x8004130A
	SCHED_E_TASK_NOT_RUNNING                          = 0x8004130B
	SCHED_E_SERVICE_NOT_INSTALLED                     = 0x8004130C
	SCHED_E_CANNOT_OPEN_TASK                          = 0x8004130D
	SCHED_E_INVALID_TASK                              = 0x8004130E
	SCHED_E_ACCOUNT_INFORMATION_SET_NOT               = 0x8004130F
	SCHED_E_ACCOUNT_NAME_NOT_FOUND                    = 0x80041310
	SCHED_E_ACCOUNT_DBASE_CORRUPT                     = 0x80041311
	SCHED_E_NO_SECURITY_SERVICES                      = 0x80041312
	SCHED_E_UNKNOWN_OBJECT_VERSION                    = 0x80041313
	SCHED_E_UNSUPPORTED_ACCOUNT_OPTION                = 0x80041314
	SCHED_E_SERVICE_NOT_RUNNING                       = 0x80041315
	SCHED_E_UNEXPECTEDNODE                            = 0x80041316
	SCHED_E_NAMESPACE                                 = 0x80041317
	SCHED_E_INVALIDVALUE                              = 0x80041318
	SCHED_E_MISSINGNODE                               = 0x80041319
	SCHED_E_MALFORMEDXML                              = 0x8004131A
	SCHED_S_SOME_TRIGGERS_FAILED                      = 0x0004131B
	SCHED_S_BATCH_LOGON_PROBLEM                       = 0x0004131C
	SCHED_E_TOO_MANY_NODES                            = 0x8004131D
	SCHED_E_PAST_END_BOUNDARY                         = 0x8004131E
	SCHED_E_ALREADY_RUNNING                           = 0x8004131F
	SCHED_E_USER_NOT_LOGGED_ON                        = 0x80041320
	SCHED_E_INVALID_TASK_HASH                         = 0x80041321
	SCHED_E_SERVICE_NOT_AVAILABLE                     = 0x80041322
	SCHED_E_SERVICE_TOO_BUSY                          = 0x80041323
	SCHED_E_TASK_ATTEMPTED                            = 0x80041324
	SCHED_S_TASK_QUEUED                               = 0x00041325
	SCHED_E_TASK_DISABLED                             = 0x80041326
	SCHED_E_TASK_NOT_V1_COMPAT                        = 0x80041327
	SCHED_E_START_ON_DEMAND                           = 0x80041328
)

const (
	CO_E_CLASS_CREATE_FAILED     = 0x80080001
	CO_E_SCM_ERROR               = 0x80080002
	CO_E_SCM_RPC_FAILURE         = 0x80080003
	CO_E_BAD_PATH                = 0x80080004
	CO_E_SERVER_EXEC_FAILURE     = 0x80080005
	CO_E_OBJSRV_RPC_FAILURE      = 0x80080006
	MK_E_NO_NORMALIZED           = 0x80080007
	CO_E_SERVER_STOPPING         = 0x80080008
	MEM_E_INVALID_ROOT           = 0x80080009
	MEM_E_INVALID_LINK           = 0x80080010
	MEM_E_INVALID_SIZE           = 0x80080011
	CO_S_NOTALLINTERFACES        = 0x00080012
	CO_S_MACHINENAMENOTFOUND     = 0x00080013
	CO_E_MISSING_DISPLAYNAME     = 0x80080015
	CO_E_RUNAS_VALUE_MUST_BE_AAA = 0x80080016
	CO_E_ELEVATION_DISABLED      = 0x80080017
)

const (
	DISP_E_UNKNOWNINTERFACE        = 0x80020001
	DISP_E_MEMBERNOTFOUND          = 0x80020003
	DISP_E_PARAMNOTFOUND           = 0x80020004
	DISP_E_TYPEMISMATCH            = 0x80020005
	DISP_E_UNKNOWNNAME             = 0x80020006
	DISP_E_NONAMEDARGS             = 0x80020007
	DISP_E_BADVARTYPE              = 0x80020008
	DISP_E_EXCEPTION               = 0x80020009
	DISP_E_OVERFLOW                = 0x8002000A
	DISP_E_BADINDEX                = 0x8002000B
	DISP_E_UNKNOWNLCID             = 0x8002000C
	DISP_E_ARRAYISLOCKED           = 0x8002000D
	DISP_E_BADPARAMCOUNT           = 0x8002000E
	DISP_E_PARAMNOTOPTIONAL        = 0x8002000F
	DISP_E_BADCALLEE               = 0x80020010
	DISP_E_NOTACOLLECTION          = 0x80020011
	DISP_E_DIVBYZERO               = 0x80020012
	DISP_E_BUFFERTOOSMALL          = 0x80020013
	TYPE_E_BUFFERTOOSMALL          = 0x80028016
	TYPE_E_FIELDNOTFOUND           = 0x80028017
	TYPE_E_INVDATAREAD             = 0x80028018
	TYPE_E_UNSUPFORMAT             = 0x80028019
	TYPE_E_REGISTRYACCESS          = 0x8002801C
	TYPE_E_LIBNOTREGISTERED        = 0x8002801D
	TYPE_E_UNDEFINEDTYPE           = 0x80028027
	TYPE_E_QUALIFIEDNAMEDISALLOWED = 0x80028028
	TYPE_E_INVALIDSTATE            = 0x80028029
	TYPE_E_WRONGTYPEKIND           = 0x8002802A
	TYPE_E_ELEMENTNOTFOUND         = 0x8002802B
	TYPE_E_AMBIGUOUSNAME           = 0x8002802C
	TYPE_E_NAMECONFLICT            = 0x8002802D
	TYPE_E_UNKNOWNLCID             = 0x8002802E
	TYPE_E_DLLFUNCTIONNOTFOUND     = 0x8002802F
	TYPE_E_BADMODULEKIND           = 0x800288BD
	TYPE_E_SIZETOOBIG              = 0x800288C5
	TYPE_E_DUPLICATEID             = 0x800288C6
	TYPE_E_INVALIDID               = 0x800288CF
	TYPE_E_TYPEMISMATCH            = 0x80028CA0
	TYPE_E_OUTOFBOUNDS             = 0x80028CA1
	TYPE_E_IOERROR                 = 0x80028CA2
	TYPE_E_CANTCREATETMPFILE       = 0x80028CA3
	TYPE_E_CANTLOADLIBRARY         = 0x80028C4A
	TYPE_E_INCONSISTENTPROPFUNCS   = 0x80028C83
	TYPE_E_CIRCULARTYPE            = 0x80028C84
)

const (
	RPC_E_CALL_REJECTED               = 0x80010001
	RPC_E_CALL_CANCELED               = 0x80010002
	RPC_E_CANTPOST_INSENDCALL         = 0x80010003
	RPC_E_CANTCALLOUT_INASYNCCALL     = 0x80010004
	RPC_E_CANTCALLOUT_INEXTERNALCALL  = 0x80010005
	RPC_E_CONNECTION_TERMINATED       = 0x80010006
	RPC_E_SERVER_DIED                 = 0x80010007
	RPC_E_CLIENT_DIED                 = 0x80010008
	RPC_E_INVALID_DATAPACKET          = 0x80010009
	RPC_E_CANTTRANSMIT_CALL           = 0x8001000A
	RPC_E_CLIENT_CANTMARSHAL_DATA     = 0x8001000B
	RPC_E_CLIENT_CANTUNMARSHAL_DATA   = 0x8001000C
	RPC_E_SERVER_CANTMARSHAL_DATA     = 0x8001000D
	RPC_E_SERVER_CANTUNMARSHAL_DATA   = 0x8001000E
	RPC_E_INVALID_DATA                = 0x8001000F
	RPC_E_INVALID_PARAMETER           = 0x80010010
	RPC_E_CANTCALLOUT_AGAIN           = 0x80010011
	RPC_E_SERVER_DIED_DNE             = 0x80010012
	RPC_E_SYS_CALL_FAILED             = 0x80010100
	RPC_E_OUT_OF_RESOURCES            = 0x80010101
	RPC_E_ATTEMPTED_MULTITHREAD       = 0x80010102
	RPC_E_NOT_REGISTERED              = 0x80010103
	RPC_E_FAULT                       = 0x80010104
	RPC_E_SERVERFAULT                 = 0x80010105
	RPC_E_CHANGED_MODE                = 0x80010106
	RPC_E_INVALIDMETHOD               = 0x80010107
	RPC_E_DISCONNECTED                = 0x80010108
	RPC_E_RETRY                       = 0x80010109
	RPC_E_SERVERCALL_RETRYLATER       = 0x8001010A
	RPC_E_SERVERCALL_REJECTED         = 0x8001010B
	RPC_E_INVALID_CALLDATA            = 0x8001010C
	RPC_E_CANTCALLOUT_ININPUTSYNCCALL = 0x8001010D
	RPC_E_WRONG_THREAD                = 0x8001010E
	RPC_E_THREAD_NOT_INIT             = 0x8001010F
	RPC_E_VERSION_MISMATCH            = 0x80010110
	RPC_E_INVALID_HEADER              = 0x80010111
	RPC_E_INVALID_EXTENSION           = 0x80010112
	RPC_E_INVALID_IPID                = 0x80010113
	RPC_E_INVALID_OBJECT              = 0x80010114
	RPC_S_CALLPENDING                 = 0x80010115
	RPC_S_WAITONTIMER                 = 0x80010116
	RPC_E_CALL_COMPLETE               = 0x80010117
	RPC_E_UNSECURE_CALL               = 0x80010118
	RPC_E_TOO_LATE                    = 0x80010119
	RPC_E_NO_GOOD_SECURITY_PACKAGES   = 0x8001011A
	RPC_E_ACCESS_DENIED               = 0x8001011B
	RPC_E_REMOTE_DISABLED             = 0x8001011C
	RPC_E_INVALID_OBJREF              = 0x8001011D
	RPC_E_NO_CONTEXT                  = 0x8001011E
	RPC_E_TIMEOUT                     = 0x8001011F
	RPC_E_NO_SYNC                     = 0x80010120
	RPC_E_FULLSIC_REQUIRED            = 0x80010121
	RPC_E_INVALID_STD_NAME            = 0x80010122
	CO_E_FAILEDTOIMPERSONATE          = 0x80010123
	CO_E_FAILEDTOGETSECCTX            = 0x80010124
	CO_E_FAILEDTOOPENTHREADTOKEN      = 0x80010125
	CO_E_FAILEDTOGETTOKENINFO         = 0x80010126
	CO_E_TRUSTEEDOESNTMATCHCLIENT     = 0x80010127
	CO_E_FAILEDTOQUERYCLIENTBLANKET   = 0x80010128
	CO_E_FAILEDTOSETDACL              = 0x80010129
	CO_E_ACCESSCHECKFAILED            = 0x8001012A
	CO_E_NETACCESSAPIFAILED           = 0x8001012B
	CO_E_WRONGTRUSTEENAMESYNTAX       = 0x8001012C
	CO_E_INVALIDSID                   = 0x8001012D
	CO_E_CONVERSIONFAILED             = 0x8001012E
	CO_E_NOMATCHINGSIDFOUND           = 0x8001012F
	CO_E_LOOKUPACCSIDFAILED           = 0x80010130
	CO_E_NOMATCHINGNAMEFOUND          = 0x80010131
	CO_E_LOOKUPACCNAMEFAILED          = 0x80010132
	CO_E_SETSERLHNDLFAILED            = 0x80010133
	CO_E_FAILEDTOGETWINDIR            = 0x80010134
	CO_E_PATHTOOLONG                  = 0x80010135
	CO_E_FAILEDTOGENUUID              = 0x80010136
	CO_E_FAILEDTOCREATEFILE           = 0x80010137
	CO_E_FAILEDTOCLOSEHANDLE          = 0x80010138
	CO_E_EXCEEDSYSACLLIMIT            = 0x80010139
	CO_E_ACESINWRONGORDER             = 0x8001013A
	CO_E_INCOMPATIBLESTREAMVERSION    = 0x8001013B
	CO_E_FAILEDTOOPENPROCESSTOKEN     = 0x8001013C
	CO_E_DECODEFAILED                 = 0x8001013D
	CO_E_ACNOTINITIALIZED             = 0x8001013E
	CO_E_CANCEL_DISABLED              = 0x8001013F
	RPC_E_UNEXPECTED                  = 0x8001FFFF
)
